package com.chris.demo.core.auto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class bankAllotSerialDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_BANK_ALLOT_SERIAL
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_BANK_ALLOT_SERIAL
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_BANK_ALLOT_SERIAL
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BANK_ALLOT_SERIAL
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public bankAllotSerialDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BANK_ALLOT_SERIAL
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BANK_ALLOT_SERIAL
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BANK_ALLOT_SERIAL
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BANK_ALLOT_SERIAL
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BANK_ALLOT_SERIAL
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BANK_ALLOT_SERIAL
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BANK_ALLOT_SERIAL
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BANK_ALLOT_SERIAL
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BANK_ALLOT_SERIAL
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_BANK_ALLOT_SERIAL
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_BANK_ALLOT_SERIAL
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTxnTypeIsNull() {
            addCriterion("txn_type is null");
            return (Criteria) this;
        }

        public Criteria andTxnTypeIsNotNull() {
            addCriterion("txn_type is not null");
            return (Criteria) this;
        }

        public Criteria andTxnTypeEqualTo(String value) {
            addCriterion("txn_type =", value, "txnType");
            return (Criteria) this;
        }

        public Criteria andTxnTypeNotEqualTo(String value) {
            addCriterion("txn_type <>", value, "txnType");
            return (Criteria) this;
        }

        public Criteria andTxnTypeGreaterThan(String value) {
            addCriterion("txn_type >", value, "txnType");
            return (Criteria) this;
        }

        public Criteria andTxnTypeGreaterThanOrEqualTo(String value) {
            addCriterion("txn_type >=", value, "txnType");
            return (Criteria) this;
        }

        public Criteria andTxnTypeLessThan(String value) {
            addCriterion("txn_type <", value, "txnType");
            return (Criteria) this;
        }

        public Criteria andTxnTypeLessThanOrEqualTo(String value) {
            addCriterion("txn_type <=", value, "txnType");
            return (Criteria) this;
        }

        public Criteria andTxnTypeLike(String value) {
            addCriterion("txn_type like", value, "txnType");
            return (Criteria) this;
        }

        public Criteria andTxnTypeNotLike(String value) {
            addCriterion("txn_type not like", value, "txnType");
            return (Criteria) this;
        }

        public Criteria andTxnTypeIn(List<String> values) {
            addCriterion("txn_type in", values, "txnType");
            return (Criteria) this;
        }

        public Criteria andTxnTypeNotIn(List<String> values) {
            addCriterion("txn_type not in", values, "txnType");
            return (Criteria) this;
        }

        public Criteria andTxnTypeBetween(String value1, String value2) {
            addCriterion("txn_type between", value1, value2, "txnType");
            return (Criteria) this;
        }

        public Criteria andTxnTypeNotBetween(String value1, String value2) {
            addCriterion("txn_type not between", value1, value2, "txnType");
            return (Criteria) this;
        }

        public Criteria andSerialNoIsNull() {
            addCriterion("serial_no is null");
            return (Criteria) this;
        }

        public Criteria andSerialNoIsNotNull() {
            addCriterion("serial_no is not null");
            return (Criteria) this;
        }

        public Criteria andSerialNoEqualTo(String value) {
            addCriterion("serial_no =", value, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoNotEqualTo(String value) {
            addCriterion("serial_no <>", value, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoGreaterThan(String value) {
            addCriterion("serial_no >", value, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoGreaterThanOrEqualTo(String value) {
            addCriterion("serial_no >=", value, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoLessThan(String value) {
            addCriterion("serial_no <", value, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoLessThanOrEqualTo(String value) {
            addCriterion("serial_no <=", value, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoLike(String value) {
            addCriterion("serial_no like", value, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoNotLike(String value) {
            addCriterion("serial_no not like", value, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoIn(List<String> values) {
            addCriterion("serial_no in", values, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoNotIn(List<String> values) {
            addCriterion("serial_no not in", values, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoBetween(String value1, String value2) {
            addCriterion("serial_no between", value1, value2, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoNotBetween(String value1, String value2) {
            addCriterion("serial_no not between", value1, value2, "serialNo");
            return (Criteria) this;
        }

        public Criteria andOriSerialNoIsNull() {
            addCriterion("ori_serial_no is null");
            return (Criteria) this;
        }

        public Criteria andOriSerialNoIsNotNull() {
            addCriterion("ori_serial_no is not null");
            return (Criteria) this;
        }

        public Criteria andOriSerialNoEqualTo(String value) {
            addCriterion("ori_serial_no =", value, "oriSerialNo");
            return (Criteria) this;
        }

        public Criteria andOriSerialNoNotEqualTo(String value) {
            addCriterion("ori_serial_no <>", value, "oriSerialNo");
            return (Criteria) this;
        }

        public Criteria andOriSerialNoGreaterThan(String value) {
            addCriterion("ori_serial_no >", value, "oriSerialNo");
            return (Criteria) this;
        }

        public Criteria andOriSerialNoGreaterThanOrEqualTo(String value) {
            addCriterion("ori_serial_no >=", value, "oriSerialNo");
            return (Criteria) this;
        }

        public Criteria andOriSerialNoLessThan(String value) {
            addCriterion("ori_serial_no <", value, "oriSerialNo");
            return (Criteria) this;
        }

        public Criteria andOriSerialNoLessThanOrEqualTo(String value) {
            addCriterion("ori_serial_no <=", value, "oriSerialNo");
            return (Criteria) this;
        }

        public Criteria andOriSerialNoLike(String value) {
            addCriterion("ori_serial_no like", value, "oriSerialNo");
            return (Criteria) this;
        }

        public Criteria andOriSerialNoNotLike(String value) {
            addCriterion("ori_serial_no not like", value, "oriSerialNo");
            return (Criteria) this;
        }

        public Criteria andOriSerialNoIn(List<String> values) {
            addCriterion("ori_serial_no in", values, "oriSerialNo");
            return (Criteria) this;
        }

        public Criteria andOriSerialNoNotIn(List<String> values) {
            addCriterion("ori_serial_no not in", values, "oriSerialNo");
            return (Criteria) this;
        }

        public Criteria andOriSerialNoBetween(String value1, String value2) {
            addCriterion("ori_serial_no between", value1, value2, "oriSerialNo");
            return (Criteria) this;
        }

        public Criteria andOriSerialNoNotBetween(String value1, String value2) {
            addCriterion("ori_serial_no not between", value1, value2, "oriSerialNo");
            return (Criteria) this;
        }

        public Criteria andBankTxnNoIsNull() {
            addCriterion("bank_txn_no is null");
            return (Criteria) this;
        }

        public Criteria andBankTxnNoIsNotNull() {
            addCriterion("bank_txn_no is not null");
            return (Criteria) this;
        }

        public Criteria andBankTxnNoEqualTo(String value) {
            addCriterion("bank_txn_no =", value, "bankTxnNo");
            return (Criteria) this;
        }

        public Criteria andBankTxnNoNotEqualTo(String value) {
            addCriterion("bank_txn_no <>", value, "bankTxnNo");
            return (Criteria) this;
        }

        public Criteria andBankTxnNoGreaterThan(String value) {
            addCriterion("bank_txn_no >", value, "bankTxnNo");
            return (Criteria) this;
        }

        public Criteria andBankTxnNoGreaterThanOrEqualTo(String value) {
            addCriterion("bank_txn_no >=", value, "bankTxnNo");
            return (Criteria) this;
        }

        public Criteria andBankTxnNoLessThan(String value) {
            addCriterion("bank_txn_no <", value, "bankTxnNo");
            return (Criteria) this;
        }

        public Criteria andBankTxnNoLessThanOrEqualTo(String value) {
            addCriterion("bank_txn_no <=", value, "bankTxnNo");
            return (Criteria) this;
        }

        public Criteria andBankTxnNoLike(String value) {
            addCriterion("bank_txn_no like", value, "bankTxnNo");
            return (Criteria) this;
        }

        public Criteria andBankTxnNoNotLike(String value) {
            addCriterion("bank_txn_no not like", value, "bankTxnNo");
            return (Criteria) this;
        }

        public Criteria andBankTxnNoIn(List<String> values) {
            addCriterion("bank_txn_no in", values, "bankTxnNo");
            return (Criteria) this;
        }

        public Criteria andBankTxnNoNotIn(List<String> values) {
            addCriterion("bank_txn_no not in", values, "bankTxnNo");
            return (Criteria) this;
        }

        public Criteria andBankTxnNoBetween(String value1, String value2) {
            addCriterion("bank_txn_no between", value1, value2, "bankTxnNo");
            return (Criteria) this;
        }

        public Criteria andBankTxnNoNotBetween(String value1, String value2) {
            addCriterion("bank_txn_no not between", value1, value2, "bankTxnNo");
            return (Criteria) this;
        }

        public Criteria andTxnStatIsNull() {
            addCriterion("txn_stat is null");
            return (Criteria) this;
        }

        public Criteria andTxnStatIsNotNull() {
            addCriterion("txn_stat is not null");
            return (Criteria) this;
        }

        public Criteria andTxnStatEqualTo(String value) {
            addCriterion("txn_stat =", value, "txnStat");
            return (Criteria) this;
        }

        public Criteria andTxnStatNotEqualTo(String value) {
            addCriterion("txn_stat <>", value, "txnStat");
            return (Criteria) this;
        }

        public Criteria andTxnStatGreaterThan(String value) {
            addCriterion("txn_stat >", value, "txnStat");
            return (Criteria) this;
        }

        public Criteria andTxnStatGreaterThanOrEqualTo(String value) {
            addCriterion("txn_stat >=", value, "txnStat");
            return (Criteria) this;
        }

        public Criteria andTxnStatLessThan(String value) {
            addCriterion("txn_stat <", value, "txnStat");
            return (Criteria) this;
        }

        public Criteria andTxnStatLessThanOrEqualTo(String value) {
            addCriterion("txn_stat <=", value, "txnStat");
            return (Criteria) this;
        }

        public Criteria andTxnStatLike(String value) {
            addCriterion("txn_stat like", value, "txnStat");
            return (Criteria) this;
        }

        public Criteria andTxnStatNotLike(String value) {
            addCriterion("txn_stat not like", value, "txnStat");
            return (Criteria) this;
        }

        public Criteria andTxnStatIn(List<String> values) {
            addCriterion("txn_stat in", values, "txnStat");
            return (Criteria) this;
        }

        public Criteria andTxnStatNotIn(List<String> values) {
            addCriterion("txn_stat not in", values, "txnStat");
            return (Criteria) this;
        }

        public Criteria andTxnStatBetween(String value1, String value2) {
            addCriterion("txn_stat between", value1, value2, "txnStat");
            return (Criteria) this;
        }

        public Criteria andTxnStatNotBetween(String value1, String value2) {
            addCriterion("txn_stat not between", value1, value2, "txnStat");
            return (Criteria) this;
        }

        public Criteria andPayerCustIdIsNull() {
            addCriterion("payer_cust_id is null");
            return (Criteria) this;
        }

        public Criteria andPayerCustIdIsNotNull() {
            addCriterion("payer_cust_id is not null");
            return (Criteria) this;
        }

        public Criteria andPayerCustIdEqualTo(String value) {
            addCriterion("payer_cust_id =", value, "payerCustId");
            return (Criteria) this;
        }

        public Criteria andPayerCustIdNotEqualTo(String value) {
            addCriterion("payer_cust_id <>", value, "payerCustId");
            return (Criteria) this;
        }

        public Criteria andPayerCustIdGreaterThan(String value) {
            addCriterion("payer_cust_id >", value, "payerCustId");
            return (Criteria) this;
        }

        public Criteria andPayerCustIdGreaterThanOrEqualTo(String value) {
            addCriterion("payer_cust_id >=", value, "payerCustId");
            return (Criteria) this;
        }

        public Criteria andPayerCustIdLessThan(String value) {
            addCriterion("payer_cust_id <", value, "payerCustId");
            return (Criteria) this;
        }

        public Criteria andPayerCustIdLessThanOrEqualTo(String value) {
            addCriterion("payer_cust_id <=", value, "payerCustId");
            return (Criteria) this;
        }

        public Criteria andPayerCustIdLike(String value) {
            addCriterion("payer_cust_id like", value, "payerCustId");
            return (Criteria) this;
        }

        public Criteria andPayerCustIdNotLike(String value) {
            addCriterion("payer_cust_id not like", value, "payerCustId");
            return (Criteria) this;
        }

        public Criteria andPayerCustIdIn(List<String> values) {
            addCriterion("payer_cust_id in", values, "payerCustId");
            return (Criteria) this;
        }

        public Criteria andPayerCustIdNotIn(List<String> values) {
            addCriterion("payer_cust_id not in", values, "payerCustId");
            return (Criteria) this;
        }

        public Criteria andPayerCustIdBetween(String value1, String value2) {
            addCriterion("payer_cust_id between", value1, value2, "payerCustId");
            return (Criteria) this;
        }

        public Criteria andPayerCustIdNotBetween(String value1, String value2) {
            addCriterion("payer_cust_id not between", value1, value2, "payerCustId");
            return (Criteria) this;
        }

        public Criteria andPayeeCustIdIsNull() {
            addCriterion("payee_cust_id is null");
            return (Criteria) this;
        }

        public Criteria andPayeeCustIdIsNotNull() {
            addCriterion("payee_cust_id is not null");
            return (Criteria) this;
        }

        public Criteria andPayeeCustIdEqualTo(String value) {
            addCriterion("payee_cust_id =", value, "payeeCustId");
            return (Criteria) this;
        }

        public Criteria andPayeeCustIdNotEqualTo(String value) {
            addCriterion("payee_cust_id <>", value, "payeeCustId");
            return (Criteria) this;
        }

        public Criteria andPayeeCustIdGreaterThan(String value) {
            addCriterion("payee_cust_id >", value, "payeeCustId");
            return (Criteria) this;
        }

        public Criteria andPayeeCustIdGreaterThanOrEqualTo(String value) {
            addCriterion("payee_cust_id >=", value, "payeeCustId");
            return (Criteria) this;
        }

        public Criteria andPayeeCustIdLessThan(String value) {
            addCriterion("payee_cust_id <", value, "payeeCustId");
            return (Criteria) this;
        }

        public Criteria andPayeeCustIdLessThanOrEqualTo(String value) {
            addCriterion("payee_cust_id <=", value, "payeeCustId");
            return (Criteria) this;
        }

        public Criteria andPayeeCustIdLike(String value) {
            addCriterion("payee_cust_id like", value, "payeeCustId");
            return (Criteria) this;
        }

        public Criteria andPayeeCustIdNotLike(String value) {
            addCriterion("payee_cust_id not like", value, "payeeCustId");
            return (Criteria) this;
        }

        public Criteria andPayeeCustIdIn(List<String> values) {
            addCriterion("payee_cust_id in", values, "payeeCustId");
            return (Criteria) this;
        }

        public Criteria andPayeeCustIdNotIn(List<String> values) {
            addCriterion("payee_cust_id not in", values, "payeeCustId");
            return (Criteria) this;
        }

        public Criteria andPayeeCustIdBetween(String value1, String value2) {
            addCriterion("payee_cust_id between", value1, value2, "payeeCustId");
            return (Criteria) this;
        }

        public Criteria andPayeeCustIdNotBetween(String value1, String value2) {
            addCriterion("payee_cust_id not between", value1, value2, "payeeCustId");
            return (Criteria) this;
        }

        public Criteria andTxnAmtIsNull() {
            addCriterion("txn_amt is null");
            return (Criteria) this;
        }

        public Criteria andTxnAmtIsNotNull() {
            addCriterion("txn_amt is not null");
            return (Criteria) this;
        }

        public Criteria andTxnAmtEqualTo(String value) {
            addCriterion("txn_amt =", value, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andTxnAmtNotEqualTo(String value) {
            addCriterion("txn_amt <>", value, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andTxnAmtGreaterThan(String value) {
            addCriterion("txn_amt >", value, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andTxnAmtGreaterThanOrEqualTo(String value) {
            addCriterion("txn_amt >=", value, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andTxnAmtLessThan(String value) {
            addCriterion("txn_amt <", value, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andTxnAmtLessThanOrEqualTo(String value) {
            addCriterion("txn_amt <=", value, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andTxnAmtLike(String value) {
            addCriterion("txn_amt like", value, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andTxnAmtNotLike(String value) {
            addCriterion("txn_amt not like", value, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andTxnAmtIn(List<String> values) {
            addCriterion("txn_amt in", values, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andTxnAmtNotIn(List<String> values) {
            addCriterion("txn_amt not in", values, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andTxnAmtBetween(String value1, String value2) {
            addCriterion("txn_amt between", value1, value2, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andTxnAmtNotBetween(String value1, String value2) {
            addCriterion("txn_amt not between", value1, value2, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andPaybillNoIsNull() {
            addCriterion("paybill_no is null");
            return (Criteria) this;
        }

        public Criteria andPaybillNoIsNotNull() {
            addCriterion("paybill_no is not null");
            return (Criteria) this;
        }

        public Criteria andPaybillNoEqualTo(String value) {
            addCriterion("paybill_no =", value, "paybillNo");
            return (Criteria) this;
        }

        public Criteria andPaybillNoNotEqualTo(String value) {
            addCriterion("paybill_no <>", value, "paybillNo");
            return (Criteria) this;
        }

        public Criteria andPaybillNoGreaterThan(String value) {
            addCriterion("paybill_no >", value, "paybillNo");
            return (Criteria) this;
        }

        public Criteria andPaybillNoGreaterThanOrEqualTo(String value) {
            addCriterion("paybill_no >=", value, "paybillNo");
            return (Criteria) this;
        }

        public Criteria andPaybillNoLessThan(String value) {
            addCriterion("paybill_no <", value, "paybillNo");
            return (Criteria) this;
        }

        public Criteria andPaybillNoLessThanOrEqualTo(String value) {
            addCriterion("paybill_no <=", value, "paybillNo");
            return (Criteria) this;
        }

        public Criteria andPaybillNoLike(String value) {
            addCriterion("paybill_no like", value, "paybillNo");
            return (Criteria) this;
        }

        public Criteria andPaybillNoNotLike(String value) {
            addCriterion("paybill_no not like", value, "paybillNo");
            return (Criteria) this;
        }

        public Criteria andPaybillNoIn(List<String> values) {
            addCriterion("paybill_no in", values, "paybillNo");
            return (Criteria) this;
        }

        public Criteria andPaybillNoNotIn(List<String> values) {
            addCriterion("paybill_no not in", values, "paybillNo");
            return (Criteria) this;
        }

        public Criteria andPaybillNoBetween(String value1, String value2) {
            addCriterion("paybill_no between", value1, value2, "paybillNo");
            return (Criteria) this;
        }

        public Criteria andPaybillNoNotBetween(String value1, String value2) {
            addCriterion("paybill_no not between", value1, value2, "paybillNo");
            return (Criteria) this;
        }

        public Criteria andQryTimesIsNull() {
            addCriterion("qry_times is null");
            return (Criteria) this;
        }

        public Criteria andQryTimesIsNotNull() {
            addCriterion("qry_times is not null");
            return (Criteria) this;
        }

        public Criteria andQryTimesEqualTo(Byte value) {
            addCriterion("qry_times =", value, "qryTimes");
            return (Criteria) this;
        }

        public Criteria andQryTimesNotEqualTo(Byte value) {
            addCriterion("qry_times <>", value, "qryTimes");
            return (Criteria) this;
        }

        public Criteria andQryTimesGreaterThan(Byte value) {
            addCriterion("qry_times >", value, "qryTimes");
            return (Criteria) this;
        }

        public Criteria andQryTimesGreaterThanOrEqualTo(Byte value) {
            addCriterion("qry_times >=", value, "qryTimes");
            return (Criteria) this;
        }

        public Criteria andQryTimesLessThan(Byte value) {
            addCriterion("qry_times <", value, "qryTimes");
            return (Criteria) this;
        }

        public Criteria andQryTimesLessThanOrEqualTo(Byte value) {
            addCriterion("qry_times <=", value, "qryTimes");
            return (Criteria) this;
        }

        public Criteria andQryTimesIn(List<Byte> values) {
            addCriterion("qry_times in", values, "qryTimes");
            return (Criteria) this;
        }

        public Criteria andQryTimesNotIn(List<Byte> values) {
            addCriterion("qry_times not in", values, "qryTimes");
            return (Criteria) this;
        }

        public Criteria andQryTimesBetween(Byte value1, Byte value2) {
            addCriterion("qry_times between", value1, value2, "qryTimes");
            return (Criteria) this;
        }

        public Criteria andQryTimesNotBetween(Byte value1, Byte value2) {
            addCriterion("qry_times not between", value1, value2, "qryTimes");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andCoopBankIsNull() {
            addCriterion("coop_bank is null");
            return (Criteria) this;
        }

        public Criteria andCoopBankIsNotNull() {
            addCriterion("coop_bank is not null");
            return (Criteria) this;
        }

        public Criteria andCoopBankEqualTo(String value) {
            addCriterion("coop_bank =", value, "coopBank");
            return (Criteria) this;
        }

        public Criteria andCoopBankNotEqualTo(String value) {
            addCriterion("coop_bank <>", value, "coopBank");
            return (Criteria) this;
        }

        public Criteria andCoopBankGreaterThan(String value) {
            addCriterion("coop_bank >", value, "coopBank");
            return (Criteria) this;
        }

        public Criteria andCoopBankGreaterThanOrEqualTo(String value) {
            addCriterion("coop_bank >=", value, "coopBank");
            return (Criteria) this;
        }

        public Criteria andCoopBankLessThan(String value) {
            addCriterion("coop_bank <", value, "coopBank");
            return (Criteria) this;
        }

        public Criteria andCoopBankLessThanOrEqualTo(String value) {
            addCriterion("coop_bank <=", value, "coopBank");
            return (Criteria) this;
        }

        public Criteria andCoopBankLike(String value) {
            addCriterion("coop_bank like", value, "coopBank");
            return (Criteria) this;
        }

        public Criteria andCoopBankNotLike(String value) {
            addCriterion("coop_bank not like", value, "coopBank");
            return (Criteria) this;
        }

        public Criteria andCoopBankIn(List<String> values) {
            addCriterion("coop_bank in", values, "coopBank");
            return (Criteria) this;
        }

        public Criteria andCoopBankNotIn(List<String> values) {
            addCriterion("coop_bank not in", values, "coopBank");
            return (Criteria) this;
        }

        public Criteria andCoopBankBetween(String value1, String value2) {
            addCriterion("coop_bank between", value1, value2, "coopBank");
            return (Criteria) this;
        }

        public Criteria andCoopBankNotBetween(String value1, String value2) {
            addCriterion("coop_bank not between", value1, value2, "coopBank");
            return (Criteria) this;
        }

        public Criteria andBankResInfoIsNull() {
            addCriterion("bank_res_info is null");
            return (Criteria) this;
        }

        public Criteria andBankResInfoIsNotNull() {
            addCriterion("bank_res_info is not null");
            return (Criteria) this;
        }

        public Criteria andBankResInfoEqualTo(String value) {
            addCriterion("bank_res_info =", value, "bankResInfo");
            return (Criteria) this;
        }

        public Criteria andBankResInfoNotEqualTo(String value) {
            addCriterion("bank_res_info <>", value, "bankResInfo");
            return (Criteria) this;
        }

        public Criteria andBankResInfoGreaterThan(String value) {
            addCriterion("bank_res_info >", value, "bankResInfo");
            return (Criteria) this;
        }

        public Criteria andBankResInfoGreaterThanOrEqualTo(String value) {
            addCriterion("bank_res_info >=", value, "bankResInfo");
            return (Criteria) this;
        }

        public Criteria andBankResInfoLessThan(String value) {
            addCriterion("bank_res_info <", value, "bankResInfo");
            return (Criteria) this;
        }

        public Criteria andBankResInfoLessThanOrEqualTo(String value) {
            addCriterion("bank_res_info <=", value, "bankResInfo");
            return (Criteria) this;
        }

        public Criteria andBankResInfoLike(String value) {
            addCriterion("bank_res_info like", value, "bankResInfo");
            return (Criteria) this;
        }

        public Criteria andBankResInfoNotLike(String value) {
            addCriterion("bank_res_info not like", value, "bankResInfo");
            return (Criteria) this;
        }

        public Criteria andBankResInfoIn(List<String> values) {
            addCriterion("bank_res_info in", values, "bankResInfo");
            return (Criteria) this;
        }

        public Criteria andBankResInfoNotIn(List<String> values) {
            addCriterion("bank_res_info not in", values, "bankResInfo");
            return (Criteria) this;
        }

        public Criteria andBankResInfoBetween(String value1, String value2) {
            addCriterion("bank_res_info between", value1, value2, "bankResInfo");
            return (Criteria) this;
        }

        public Criteria andBankResInfoNotBetween(String value1, String value2) {
            addCriterion("bank_res_info not between", value1, value2, "bankResInfo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_BANK_ALLOT_SERIAL
     *
     * @mbg.generated do_not_delete_during_merge Tue Aug 21 16:27:54 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_BANK_ALLOT_SERIAL
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}