package com.chris.demo.core.auto;

public class bankAllotSerialDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_BANK_ALLOT_SERIAL.txn_type
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    private String txnType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_BANK_ALLOT_SERIAL.serial_no
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    private String serialNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_BANK_ALLOT_SERIAL.txn_type
     *
     * @return the value of TB_BANK_ALLOT_SERIAL.txn_type
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public String getTxnType() {
        return txnType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_BANK_ALLOT_SERIAL.txn_type
     *
     * @param txnType the value for TB_BANK_ALLOT_SERIAL.txn_type
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public void setTxnType(String txnType) {
        this.txnType = txnType == null ? null : txnType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_BANK_ALLOT_SERIAL.serial_no
     *
     * @return the value of TB_BANK_ALLOT_SERIAL.serial_no
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public String getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_BANK_ALLOT_SERIAL.serial_no
     *
     * @param serialNo the value for TB_BANK_ALLOT_SERIAL.serial_no
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo == null ? null : serialNo.trim();
    }
}