package com.chris.demo.core.auto;

import java.util.Date;

public class bankAllotSerialDO extends bankAllotSerialDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_BANK_ALLOT_SERIAL.ori_serial_no
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    private String oriSerialNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_BANK_ALLOT_SERIAL.bank_txn_no
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    private String bankTxnNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_BANK_ALLOT_SERIAL.txn_stat
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    private String txnStat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_BANK_ALLOT_SERIAL.payer_cust_id
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    private String payerCustId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_BANK_ALLOT_SERIAL.payee_cust_id
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    private String payeeCustId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_BANK_ALLOT_SERIAL.txn_amt
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    private String txnAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_BANK_ALLOT_SERIAL.paybill_no
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    private String paybillNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_BANK_ALLOT_SERIAL.qry_times
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    private Byte qryTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_BANK_ALLOT_SERIAL.gmt_create
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_BANK_ALLOT_SERIAL.gmt_modified
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_BANK_ALLOT_SERIAL.coop_bank
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    private String coopBank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_BANK_ALLOT_SERIAL.bank_res_info
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    private String bankResInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_BANK_ALLOT_SERIAL.bank_ext_param
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    private String bankExtParam;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_BANK_ALLOT_SERIAL.ori_serial_no
     *
     * @return the value of TB_BANK_ALLOT_SERIAL.ori_serial_no
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public String getOriSerialNo() {
        return oriSerialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_BANK_ALLOT_SERIAL.ori_serial_no
     *
     * @param oriSerialNo the value for TB_BANK_ALLOT_SERIAL.ori_serial_no
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public void setOriSerialNo(String oriSerialNo) {
        this.oriSerialNo = oriSerialNo == null ? null : oriSerialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_BANK_ALLOT_SERIAL.bank_txn_no
     *
     * @return the value of TB_BANK_ALLOT_SERIAL.bank_txn_no
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public String getBankTxnNo() {
        return bankTxnNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_BANK_ALLOT_SERIAL.bank_txn_no
     *
     * @param bankTxnNo the value for TB_BANK_ALLOT_SERIAL.bank_txn_no
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public void setBankTxnNo(String bankTxnNo) {
        this.bankTxnNo = bankTxnNo == null ? null : bankTxnNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_BANK_ALLOT_SERIAL.txn_stat
     *
     * @return the value of TB_BANK_ALLOT_SERIAL.txn_stat
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public String getTxnStat() {
        return txnStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_BANK_ALLOT_SERIAL.txn_stat
     *
     * @param txnStat the value for TB_BANK_ALLOT_SERIAL.txn_stat
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public void setTxnStat(String txnStat) {
        this.txnStat = txnStat == null ? null : txnStat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_BANK_ALLOT_SERIAL.payer_cust_id
     *
     * @return the value of TB_BANK_ALLOT_SERIAL.payer_cust_id
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public String getPayerCustId() {
        return payerCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_BANK_ALLOT_SERIAL.payer_cust_id
     *
     * @param payerCustId the value for TB_BANK_ALLOT_SERIAL.payer_cust_id
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public void setPayerCustId(String payerCustId) {
        this.payerCustId = payerCustId == null ? null : payerCustId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_BANK_ALLOT_SERIAL.payee_cust_id
     *
     * @return the value of TB_BANK_ALLOT_SERIAL.payee_cust_id
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public String getPayeeCustId() {
        return payeeCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_BANK_ALLOT_SERIAL.payee_cust_id
     *
     * @param payeeCustId the value for TB_BANK_ALLOT_SERIAL.payee_cust_id
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public void setPayeeCustId(String payeeCustId) {
        this.payeeCustId = payeeCustId == null ? null : payeeCustId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_BANK_ALLOT_SERIAL.txn_amt
     *
     * @return the value of TB_BANK_ALLOT_SERIAL.txn_amt
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public String getTxnAmt() {
        return txnAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_BANK_ALLOT_SERIAL.txn_amt
     *
     * @param txnAmt the value for TB_BANK_ALLOT_SERIAL.txn_amt
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public void setTxnAmt(String txnAmt) {
        this.txnAmt = txnAmt == null ? null : txnAmt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_BANK_ALLOT_SERIAL.paybill_no
     *
     * @return the value of TB_BANK_ALLOT_SERIAL.paybill_no
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public String getPaybillNo() {
        return paybillNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_BANK_ALLOT_SERIAL.paybill_no
     *
     * @param paybillNo the value for TB_BANK_ALLOT_SERIAL.paybill_no
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public void setPaybillNo(String paybillNo) {
        this.paybillNo = paybillNo == null ? null : paybillNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_BANK_ALLOT_SERIAL.qry_times
     *
     * @return the value of TB_BANK_ALLOT_SERIAL.qry_times
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public Byte getQryTimes() {
        return qryTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_BANK_ALLOT_SERIAL.qry_times
     *
     * @param qryTimes the value for TB_BANK_ALLOT_SERIAL.qry_times
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public void setQryTimes(Byte qryTimes) {
        this.qryTimes = qryTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_BANK_ALLOT_SERIAL.gmt_create
     *
     * @return the value of TB_BANK_ALLOT_SERIAL.gmt_create
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_BANK_ALLOT_SERIAL.gmt_create
     *
     * @param gmtCreate the value for TB_BANK_ALLOT_SERIAL.gmt_create
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_BANK_ALLOT_SERIAL.gmt_modified
     *
     * @return the value of TB_BANK_ALLOT_SERIAL.gmt_modified
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_BANK_ALLOT_SERIAL.gmt_modified
     *
     * @param gmtModified the value for TB_BANK_ALLOT_SERIAL.gmt_modified
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_BANK_ALLOT_SERIAL.coop_bank
     *
     * @return the value of TB_BANK_ALLOT_SERIAL.coop_bank
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public String getCoopBank() {
        return coopBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_BANK_ALLOT_SERIAL.coop_bank
     *
     * @param coopBank the value for TB_BANK_ALLOT_SERIAL.coop_bank
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public void setCoopBank(String coopBank) {
        this.coopBank = coopBank == null ? null : coopBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_BANK_ALLOT_SERIAL.bank_res_info
     *
     * @return the value of TB_BANK_ALLOT_SERIAL.bank_res_info
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public String getBankResInfo() {
        return bankResInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_BANK_ALLOT_SERIAL.bank_res_info
     *
     * @param bankResInfo the value for TB_BANK_ALLOT_SERIAL.bank_res_info
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public void setBankResInfo(String bankResInfo) {
        this.bankResInfo = bankResInfo == null ? null : bankResInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_BANK_ALLOT_SERIAL.bank_ext_param
     *
     * @return the value of TB_BANK_ALLOT_SERIAL.bank_ext_param
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public String getBankExtParam() {
        return bankExtParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_BANK_ALLOT_SERIAL.bank_ext_param
     *
     * @param bankExtParam the value for TB_BANK_ALLOT_SERIAL.bank_ext_param
     *
     * @mbg.generated Tue Aug 21 16:27:54 CST 2018
     */
    public void setBankExtParam(String bankExtParam) {
        this.bankExtParam = bankExtParam == null ? null : bankExtParam.trim();
    }
}