package com.chris.demo.core.auto;

public class ChnlPayProduct {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHNL_PAY_PRODUCT.prod_id
     *
     * @mbg.generated Tue Jul 10 09:52:39 CST 2018
     */
    private String prodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHNL_PAY_PRODUCT.prod_nm
     *
     * @mbg.generated Tue Jul 10 09:52:39 CST 2018
     */
    private String prodNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHNL_PAY_PRODUCT.prod_desc
     *
     * @mbg.generated Tue Jul 10 09:52:39 CST 2018
     */
    private String prodDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHNL_PAY_PRODUCT.prod_id
     *
     * @return the value of CHNL_PAY_PRODUCT.prod_id
     *
     * @mbg.generated Tue Jul 10 09:52:39 CST 2018
     */
    public String getProdId() {
        return prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHNL_PAY_PRODUCT.prod_id
     *
     * @param prodId the value for CHNL_PAY_PRODUCT.prod_id
     *
     * @mbg.generated Tue Jul 10 09:52:39 CST 2018
     */
    public void setProdId(String prodId) {
        this.prodId = prodId == null ? null : prodId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHNL_PAY_PRODUCT.prod_nm
     *
     * @return the value of CHNL_PAY_PRODUCT.prod_nm
     *
     * @mbg.generated Tue Jul 10 09:52:39 CST 2018
     */
    public String getProdNm() {
        return prodNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHNL_PAY_PRODUCT.prod_nm
     *
     * @param prodNm the value for CHNL_PAY_PRODUCT.prod_nm
     *
     * @mbg.generated Tue Jul 10 09:52:39 CST 2018
     */
    public void setProdNm(String prodNm) {
        this.prodNm = prodNm == null ? null : prodNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHNL_PAY_PRODUCT.prod_desc
     *
     * @return the value of CHNL_PAY_PRODUCT.prod_desc
     *
     * @mbg.generated Tue Jul 10 09:52:39 CST 2018
     */
    public String getProdDesc() {
        return prodDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHNL_PAY_PRODUCT.prod_desc
     *
     * @param prodDesc the value for CHNL_PAY_PRODUCT.prod_desc
     *
     * @mbg.generated Tue Jul 10 09:52:39 CST 2018
     */
    public void setProdDesc(String prodDesc) {
        this.prodDesc = prodDesc == null ? null : prodDesc.trim();
    }
}