package com.chris.demo.core.auto;

import java.util.ArrayList;
import java.util.List;

public class ChnlPayProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CHNL_PAY_PRODUCT
     *
     * @mbg.generated Tue Jul 10 09:52:39 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CHNL_PAY_PRODUCT
     *
     * @mbg.generated Tue Jul 10 09:52:39 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CHNL_PAY_PRODUCT
     *
     * @mbg.generated Tue Jul 10 09:52:39 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHNL_PAY_PRODUCT
     *
     * @mbg.generated Tue Jul 10 09:52:39 CST 2018
     */
    public ChnlPayProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHNL_PAY_PRODUCT
     *
     * @mbg.generated Tue Jul 10 09:52:39 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHNL_PAY_PRODUCT
     *
     * @mbg.generated Tue Jul 10 09:52:39 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHNL_PAY_PRODUCT
     *
     * @mbg.generated Tue Jul 10 09:52:39 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHNL_PAY_PRODUCT
     *
     * @mbg.generated Tue Jul 10 09:52:39 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHNL_PAY_PRODUCT
     *
     * @mbg.generated Tue Jul 10 09:52:39 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHNL_PAY_PRODUCT
     *
     * @mbg.generated Tue Jul 10 09:52:39 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHNL_PAY_PRODUCT
     *
     * @mbg.generated Tue Jul 10 09:52:39 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHNL_PAY_PRODUCT
     *
     * @mbg.generated Tue Jul 10 09:52:39 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHNL_PAY_PRODUCT
     *
     * @mbg.generated Tue Jul 10 09:52:39 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHNL_PAY_PRODUCT
     *
     * @mbg.generated Tue Jul 10 09:52:39 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CHNL_PAY_PRODUCT
     *
     * @mbg.generated Tue Jul 10 09:52:39 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProdIdIsNull() {
            addCriterion("prod_id is null");
            return (Criteria) this;
        }

        public Criteria andProdIdIsNotNull() {
            addCriterion("prod_id is not null");
            return (Criteria) this;
        }

        public Criteria andProdIdEqualTo(String value) {
            addCriterion("prod_id =", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdNotEqualTo(String value) {
            addCriterion("prod_id <>", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdGreaterThan(String value) {
            addCriterion("prod_id >", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdGreaterThanOrEqualTo(String value) {
            addCriterion("prod_id >=", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdLessThan(String value) {
            addCriterion("prod_id <", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdLessThanOrEqualTo(String value) {
            addCriterion("prod_id <=", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdLike(String value) {
            addCriterion("prod_id like", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdNotLike(String value) {
            addCriterion("prod_id not like", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdIn(List<String> values) {
            addCriterion("prod_id in", values, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdNotIn(List<String> values) {
            addCriterion("prod_id not in", values, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdBetween(String value1, String value2) {
            addCriterion("prod_id between", value1, value2, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdNotBetween(String value1, String value2) {
            addCriterion("prod_id not between", value1, value2, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdNmIsNull() {
            addCriterion("prod_nm is null");
            return (Criteria) this;
        }

        public Criteria andProdNmIsNotNull() {
            addCriterion("prod_nm is not null");
            return (Criteria) this;
        }

        public Criteria andProdNmEqualTo(String value) {
            addCriterion("prod_nm =", value, "prodNm");
            return (Criteria) this;
        }

        public Criteria andProdNmNotEqualTo(String value) {
            addCriterion("prod_nm <>", value, "prodNm");
            return (Criteria) this;
        }

        public Criteria andProdNmGreaterThan(String value) {
            addCriterion("prod_nm >", value, "prodNm");
            return (Criteria) this;
        }

        public Criteria andProdNmGreaterThanOrEqualTo(String value) {
            addCriterion("prod_nm >=", value, "prodNm");
            return (Criteria) this;
        }

        public Criteria andProdNmLessThan(String value) {
            addCriterion("prod_nm <", value, "prodNm");
            return (Criteria) this;
        }

        public Criteria andProdNmLessThanOrEqualTo(String value) {
            addCriterion("prod_nm <=", value, "prodNm");
            return (Criteria) this;
        }

        public Criteria andProdNmLike(String value) {
            addCriterion("prod_nm like", value, "prodNm");
            return (Criteria) this;
        }

        public Criteria andProdNmNotLike(String value) {
            addCriterion("prod_nm not like", value, "prodNm");
            return (Criteria) this;
        }

        public Criteria andProdNmIn(List<String> values) {
            addCriterion("prod_nm in", values, "prodNm");
            return (Criteria) this;
        }

        public Criteria andProdNmNotIn(List<String> values) {
            addCriterion("prod_nm not in", values, "prodNm");
            return (Criteria) this;
        }

        public Criteria andProdNmBetween(String value1, String value2) {
            addCriterion("prod_nm between", value1, value2, "prodNm");
            return (Criteria) this;
        }

        public Criteria andProdNmNotBetween(String value1, String value2) {
            addCriterion("prod_nm not between", value1, value2, "prodNm");
            return (Criteria) this;
        }

        public Criteria andProdDescIsNull() {
            addCriterion("prod_desc is null");
            return (Criteria) this;
        }

        public Criteria andProdDescIsNotNull() {
            addCriterion("prod_desc is not null");
            return (Criteria) this;
        }

        public Criteria andProdDescEqualTo(String value) {
            addCriterion("prod_desc =", value, "prodDesc");
            return (Criteria) this;
        }

        public Criteria andProdDescNotEqualTo(String value) {
            addCriterion("prod_desc <>", value, "prodDesc");
            return (Criteria) this;
        }

        public Criteria andProdDescGreaterThan(String value) {
            addCriterion("prod_desc >", value, "prodDesc");
            return (Criteria) this;
        }

        public Criteria andProdDescGreaterThanOrEqualTo(String value) {
            addCriterion("prod_desc >=", value, "prodDesc");
            return (Criteria) this;
        }

        public Criteria andProdDescLessThan(String value) {
            addCriterion("prod_desc <", value, "prodDesc");
            return (Criteria) this;
        }

        public Criteria andProdDescLessThanOrEqualTo(String value) {
            addCriterion("prod_desc <=", value, "prodDesc");
            return (Criteria) this;
        }

        public Criteria andProdDescLike(String value) {
            addCriterion("prod_desc like", value, "prodDesc");
            return (Criteria) this;
        }

        public Criteria andProdDescNotLike(String value) {
            addCriterion("prod_desc not like", value, "prodDesc");
            return (Criteria) this;
        }

        public Criteria andProdDescIn(List<String> values) {
            addCriterion("prod_desc in", values, "prodDesc");
            return (Criteria) this;
        }

        public Criteria andProdDescNotIn(List<String> values) {
            addCriterion("prod_desc not in", values, "prodDesc");
            return (Criteria) this;
        }

        public Criteria andProdDescBetween(String value1, String value2) {
            addCriterion("prod_desc between", value1, value2, "prodDesc");
            return (Criteria) this;
        }

        public Criteria andProdDescNotBetween(String value1, String value2) {
            addCriterion("prod_desc not between", value1, value2, "prodDesc");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CHNL_PAY_PRODUCT
     *
     * @mbg.generated do_not_delete_during_merge Tue Jul 10 09:52:39 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CHNL_PAY_PRODUCT
     *
     * @mbg.generated Tue Jul 10 09:52:39 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}