package com.chris.demo.core.auto;

import java.util.Date;

public class PayFinRefund {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PAY_FIN_REFUND.SERIAL_NO
     *
     */
    private Long serialNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PAY_FIN_REFUND.OID_BILLNO
     *
     */
    private Long oidBillno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PAY_FIN_REFUND.OLD_TRADE_TIME
     *
     */
    private Date oldTradeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PAY_FIN_REFUND.OLD_TRADE_AMT
     *
     */
    private Long oldTradeAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PAY_FIN_REFUND.REFUND_AMT
     *
     */
    private Long refundAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PAY_FIN_REFUND.REFUND_CURRENCY
     *
     */
    private String refundCurrency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PAY_FIN_REFUND.REFUND_ACCTNO
     *
     */
    private String refundAcctno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PAY_FIN_REFUND.REFUND_ACCTNAME
     *
     */
    private String refundAcctname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PAY_FIN_REFUND.SOURCE
     *
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PAY_FIN_REFUND.CHNL_CODE
     *
     */
    private String chnlCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PAY_FIN_REFUND.BANK_RET_CODE
     *
     */
    private String bankRetCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PAY_FIN_REFUND.BANK_RET_MSG
     *
     */
    private String bankRetMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PAY_FIN_REFUND.BANK_SERIALNO
     *
     */
    private String bankSerialno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PAY_FIN_REFUND.SETTLE_DATE
     *
     */
    private String settleDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PAY_FIN_REFUND.STATUS
     *
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PAY_FIN_REFUND.CREATE_TIME
     *
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PAY_FIN_REFUND.MODIFY_TIME
     *
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PAY_FIN_REFUND.REMARK
     *
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PAY_FIN_REFUND.OID_REFUNDNO
     *
     */
    private Long oidRefundno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PAY_FIN_REFUND.YT_HAS_SERIALNO
     *
     */
    private String ytHasSerialno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PAY_FIN_REFUND.PROCESS_TYPE
     *
     */
    private String processType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_PAY_FIN_REFUND.WITHDRAW_NO
     *
     */
    private Long withdrawNo;

    public Long getSerialNo() {
        return serialNo;
    }

    public void setSerialNo(Long serialNo) {
        this.serialNo = serialNo;
    }

    public Long getOidBillno() {
        return oidBillno;
    }

    public void setOidBillno(Long oidBillno) {
        this.oidBillno = oidBillno;
    }

    public Date getOldTradeTime() {
        return oldTradeTime;
    }

    public void setOldTradeTime(Date oldTradeTime) {
        this.oldTradeTime = oldTradeTime;
    }

    public Long getOldTradeAmt() {
        return oldTradeAmt;
    }

    public void setOldTradeAmt(Long oldTradeAmt) {
        this.oldTradeAmt = oldTradeAmt;
    }

    public Long getRefundAmt() {
        return refundAmt;
    }

    public void setRefundAmt(Long refundAmt) {
        this.refundAmt = refundAmt;
    }

    public String getRefundCurrency() {
        return refundCurrency;
    }

    public void setRefundCurrency(String refundCurrency) {
        this.refundCurrency = refundCurrency;
    }

    public String getRefundAcctno() {
        return refundAcctno;
    }

    public void setRefundAcctno(String refundAcctno) {
        this.refundAcctno = refundAcctno;
    }

    public String getRefundAcctname() {
        return refundAcctname;
    }

    public void setRefundAcctname(String refundAcctname) {
        this.refundAcctname = refundAcctname;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public String getChnlCode() {
        return chnlCode;
    }

    public void setChnlCode(String chnlCode) {
        this.chnlCode = chnlCode;
    }

    public String getBankRetCode() {
        return bankRetCode;
    }

    public void setBankRetCode(String bankRetCode) {
        this.bankRetCode = bankRetCode;
    }

    public String getBankRetMsg() {
        return bankRetMsg;
    }

    public void setBankRetMsg(String bankRetMsg) {
        this.bankRetMsg = bankRetMsg;
    }

    public String getBankSerialno() {
        return bankSerialno;
    }

    public void setBankSerialno(String bankSerialno) {
        this.bankSerialno = bankSerialno;
    }

    public String getSettleDate() {
        return settleDate;
    }

    public void setSettleDate(String settleDate) {
        this.settleDate = settleDate;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getModifyTime() {
        return modifyTime;
    }

    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Long getOidRefundno() {
        return oidRefundno;
    }

    public void setOidRefundno(Long oidRefundno) {
        this.oidRefundno = oidRefundno;
    }

    public String getYtHasSerialno() {
        return ytHasSerialno;
    }

    public void setYtHasSerialno(String ytHasSerialno) {
        this.ytHasSerialno = ytHasSerialno;
    }

    public String getProcessType() {
        return processType;
    }

    public void setProcessType(String processType) {
        this.processType = processType;
    }

    public Long getWithdrawNo() {
        return withdrawNo;
    }

    public void setWithdrawNo(Long withdrawNo) {
        this.withdrawNo = withdrawNo;
    }
}