package com.chris.demo.core.auto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PayFinRefundExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_PAY_FIN_REFUND
     *
     * @mbg.generated Wed Jul 18 14:21:44 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_PAY_FIN_REFUND
     *
     * @mbg.generated Wed Jul 18 14:21:44 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_PAY_FIN_REFUND
     *
     * @mbg.generated Wed Jul 18 14:21:44 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PAY_FIN_REFUND
     *
     * @mbg.generated Wed Jul 18 14:21:44 CST 2018
     */
    public PayFinRefundExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PAY_FIN_REFUND
     *
     * @mbg.generated Wed Jul 18 14:21:44 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PAY_FIN_REFUND
     *
     * @mbg.generated Wed Jul 18 14:21:44 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PAY_FIN_REFUND
     *
     * @mbg.generated Wed Jul 18 14:21:44 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PAY_FIN_REFUND
     *
     * @mbg.generated Wed Jul 18 14:21:44 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PAY_FIN_REFUND
     *
     * @mbg.generated Wed Jul 18 14:21:44 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PAY_FIN_REFUND
     *
     * @mbg.generated Wed Jul 18 14:21:44 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PAY_FIN_REFUND
     *
     * @mbg.generated Wed Jul 18 14:21:44 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PAY_FIN_REFUND
     *
     * @mbg.generated Wed Jul 18 14:21:44 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PAY_FIN_REFUND
     *
     * @mbg.generated Wed Jul 18 14:21:44 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_PAY_FIN_REFUND
     *
     * @mbg.generated Wed Jul 18 14:21:44 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_PAY_FIN_REFUND
     *
     * @mbg.generated Wed Jul 18 14:21:44 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSerialNoIsNull() {
            addCriterion("SERIAL_NO is null");
            return (Criteria) this;
        }

        public Criteria andSerialNoIsNotNull() {
            addCriterion("SERIAL_NO is not null");
            return (Criteria) this;
        }

        public Criteria andSerialNoEqualTo(Long value) {
            addCriterion("SERIAL_NO =", value, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoNotEqualTo(Long value) {
            addCriterion("SERIAL_NO <>", value, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoGreaterThan(Long value) {
            addCriterion("SERIAL_NO >", value, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoGreaterThanOrEqualTo(Long value) {
            addCriterion("SERIAL_NO >=", value, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoLessThan(Long value) {
            addCriterion("SERIAL_NO <", value, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoLessThanOrEqualTo(Long value) {
            addCriterion("SERIAL_NO <=", value, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoIn(List<Long> values) {
            addCriterion("SERIAL_NO in", values, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoNotIn(List<Long> values) {
            addCriterion("SERIAL_NO not in", values, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoBetween(Long value1, Long value2) {
            addCriterion("SERIAL_NO between", value1, value2, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoNotBetween(Long value1, Long value2) {
            addCriterion("SERIAL_NO not between", value1, value2, "serialNo");
            return (Criteria) this;
        }

        public Criteria andOidBillnoIsNull() {
            addCriterion("OID_BILLNO is null");
            return (Criteria) this;
        }

        public Criteria andOidBillnoIsNotNull() {
            addCriterion("OID_BILLNO is not null");
            return (Criteria) this;
        }

        public Criteria andOidBillnoEqualTo(Long value) {
            addCriterion("OID_BILLNO =", value, "oidBillno");
            return (Criteria) this;
        }

        public Criteria andOidBillnoNotEqualTo(Long value) {
            addCriterion("OID_BILLNO <>", value, "oidBillno");
            return (Criteria) this;
        }

        public Criteria andOidBillnoGreaterThan(Long value) {
            addCriterion("OID_BILLNO >", value, "oidBillno");
            return (Criteria) this;
        }

        public Criteria andOidBillnoGreaterThanOrEqualTo(Long value) {
            addCriterion("OID_BILLNO >=", value, "oidBillno");
            return (Criteria) this;
        }

        public Criteria andOidBillnoLessThan(Long value) {
            addCriterion("OID_BILLNO <", value, "oidBillno");
            return (Criteria) this;
        }

        public Criteria andOidBillnoLessThanOrEqualTo(Long value) {
            addCriterion("OID_BILLNO <=", value, "oidBillno");
            return (Criteria) this;
        }

        public Criteria andOidBillnoIn(List<Long> values) {
            addCriterion("OID_BILLNO in", values, "oidBillno");
            return (Criteria) this;
        }

        public Criteria andOidBillnoNotIn(List<Long> values) {
            addCriterion("OID_BILLNO not in", values, "oidBillno");
            return (Criteria) this;
        }

        public Criteria andOidBillnoBetween(Long value1, Long value2) {
            addCriterion("OID_BILLNO between", value1, value2, "oidBillno");
            return (Criteria) this;
        }

        public Criteria andOidBillnoNotBetween(Long value1, Long value2) {
            addCriterion("OID_BILLNO not between", value1, value2, "oidBillno");
            return (Criteria) this;
        }

        public Criteria andOldTradeTimeIsNull() {
            addCriterion("OLD_TRADE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andOldTradeTimeIsNotNull() {
            addCriterion("OLD_TRADE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andOldTradeTimeEqualTo(Date value) {
            addCriterion("OLD_TRADE_TIME =", value, "oldTradeTime");
            return (Criteria) this;
        }

        public Criteria andOldTradeTimeNotEqualTo(Date value) {
            addCriterion("OLD_TRADE_TIME <>", value, "oldTradeTime");
            return (Criteria) this;
        }

        public Criteria andOldTradeTimeGreaterThan(Date value) {
            addCriterion("OLD_TRADE_TIME >", value, "oldTradeTime");
            return (Criteria) this;
        }

        public Criteria andOldTradeTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("OLD_TRADE_TIME >=", value, "oldTradeTime");
            return (Criteria) this;
        }

        public Criteria andOldTradeTimeLessThan(Date value) {
            addCriterion("OLD_TRADE_TIME <", value, "oldTradeTime");
            return (Criteria) this;
        }

        public Criteria andOldTradeTimeLessThanOrEqualTo(Date value) {
            addCriterion("OLD_TRADE_TIME <=", value, "oldTradeTime");
            return (Criteria) this;
        }

        public Criteria andOldTradeTimeIn(List<Date> values) {
            addCriterion("OLD_TRADE_TIME in", values, "oldTradeTime");
            return (Criteria) this;
        }

        public Criteria andOldTradeTimeNotIn(List<Date> values) {
            addCriterion("OLD_TRADE_TIME not in", values, "oldTradeTime");
            return (Criteria) this;
        }

        public Criteria andOldTradeTimeBetween(Date value1, Date value2) {
            addCriterion("OLD_TRADE_TIME between", value1, value2, "oldTradeTime");
            return (Criteria) this;
        }

        public Criteria andOldTradeTimeNotBetween(Date value1, Date value2) {
            addCriterion("OLD_TRADE_TIME not between", value1, value2, "oldTradeTime");
            return (Criteria) this;
        }

        public Criteria andOldTradeAmtIsNull() {
            addCriterion("OLD_TRADE_AMT is null");
            return (Criteria) this;
        }

        public Criteria andOldTradeAmtIsNotNull() {
            addCriterion("OLD_TRADE_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andOldTradeAmtEqualTo(Long value) {
            addCriterion("OLD_TRADE_AMT =", value, "oldTradeAmt");
            return (Criteria) this;
        }

        public Criteria andOldTradeAmtNotEqualTo(Long value) {
            addCriterion("OLD_TRADE_AMT <>", value, "oldTradeAmt");
            return (Criteria) this;
        }

        public Criteria andOldTradeAmtGreaterThan(Long value) {
            addCriterion("OLD_TRADE_AMT >", value, "oldTradeAmt");
            return (Criteria) this;
        }

        public Criteria andOldTradeAmtGreaterThanOrEqualTo(Long value) {
            addCriterion("OLD_TRADE_AMT >=", value, "oldTradeAmt");
            return (Criteria) this;
        }

        public Criteria andOldTradeAmtLessThan(Long value) {
            addCriterion("OLD_TRADE_AMT <", value, "oldTradeAmt");
            return (Criteria) this;
        }

        public Criteria andOldTradeAmtLessThanOrEqualTo(Long value) {
            addCriterion("OLD_TRADE_AMT <=", value, "oldTradeAmt");
            return (Criteria) this;
        }

        public Criteria andOldTradeAmtIn(List<Long> values) {
            addCriterion("OLD_TRADE_AMT in", values, "oldTradeAmt");
            return (Criteria) this;
        }

        public Criteria andOldTradeAmtNotIn(List<Long> values) {
            addCriterion("OLD_TRADE_AMT not in", values, "oldTradeAmt");
            return (Criteria) this;
        }

        public Criteria andOldTradeAmtBetween(Long value1, Long value2) {
            addCriterion("OLD_TRADE_AMT between", value1, value2, "oldTradeAmt");
            return (Criteria) this;
        }

        public Criteria andOldTradeAmtNotBetween(Long value1, Long value2) {
            addCriterion("OLD_TRADE_AMT not between", value1, value2, "oldTradeAmt");
            return (Criteria) this;
        }

        public Criteria andRefundAmtIsNull() {
            addCriterion("REFUND_AMT is null");
            return (Criteria) this;
        }

        public Criteria andRefundAmtIsNotNull() {
            addCriterion("REFUND_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andRefundAmtEqualTo(Long value) {
            addCriterion("REFUND_AMT =", value, "refundAmt");
            return (Criteria) this;
        }

        public Criteria andRefundAmtNotEqualTo(Long value) {
            addCriterion("REFUND_AMT <>", value, "refundAmt");
            return (Criteria) this;
        }

        public Criteria andRefundAmtGreaterThan(Long value) {
            addCriterion("REFUND_AMT >", value, "refundAmt");
            return (Criteria) this;
        }

        public Criteria andRefundAmtGreaterThanOrEqualTo(Long value) {
            addCriterion("REFUND_AMT >=", value, "refundAmt");
            return (Criteria) this;
        }

        public Criteria andRefundAmtLessThan(Long value) {
            addCriterion("REFUND_AMT <", value, "refundAmt");
            return (Criteria) this;
        }

        public Criteria andRefundAmtLessThanOrEqualTo(Long value) {
            addCriterion("REFUND_AMT <=", value, "refundAmt");
            return (Criteria) this;
        }

        public Criteria andRefundAmtIn(List<Long> values) {
            addCriterion("REFUND_AMT in", values, "refundAmt");
            return (Criteria) this;
        }

        public Criteria andRefundAmtNotIn(List<Long> values) {
            addCriterion("REFUND_AMT not in", values, "refundAmt");
            return (Criteria) this;
        }

        public Criteria andRefundAmtBetween(Long value1, Long value2) {
            addCriterion("REFUND_AMT between", value1, value2, "refundAmt");
            return (Criteria) this;
        }

        public Criteria andRefundAmtNotBetween(Long value1, Long value2) {
            addCriterion("REFUND_AMT not between", value1, value2, "refundAmt");
            return (Criteria) this;
        }

        public Criteria andRefundCurrencyIsNull() {
            addCriterion("REFUND_CURRENCY is null");
            return (Criteria) this;
        }

        public Criteria andRefundCurrencyIsNotNull() {
            addCriterion("REFUND_CURRENCY is not null");
            return (Criteria) this;
        }

        public Criteria andRefundCurrencyEqualTo(String value) {
            addCriterion("REFUND_CURRENCY =", value, "refundCurrency");
            return (Criteria) this;
        }

        public Criteria andRefundCurrencyNotEqualTo(String value) {
            addCriterion("REFUND_CURRENCY <>", value, "refundCurrency");
            return (Criteria) this;
        }

        public Criteria andRefundCurrencyGreaterThan(String value) {
            addCriterion("REFUND_CURRENCY >", value, "refundCurrency");
            return (Criteria) this;
        }

        public Criteria andRefundCurrencyGreaterThanOrEqualTo(String value) {
            addCriterion("REFUND_CURRENCY >=", value, "refundCurrency");
            return (Criteria) this;
        }

        public Criteria andRefundCurrencyLessThan(String value) {
            addCriterion("REFUND_CURRENCY <", value, "refundCurrency");
            return (Criteria) this;
        }

        public Criteria andRefundCurrencyLessThanOrEqualTo(String value) {
            addCriterion("REFUND_CURRENCY <=", value, "refundCurrency");
            return (Criteria) this;
        }

        public Criteria andRefundCurrencyLike(String value) {
            addCriterion("REFUND_CURRENCY like", value, "refundCurrency");
            return (Criteria) this;
        }

        public Criteria andRefundCurrencyNotLike(String value) {
            addCriterion("REFUND_CURRENCY not like", value, "refundCurrency");
            return (Criteria) this;
        }

        public Criteria andRefundCurrencyIn(List<String> values) {
            addCriterion("REFUND_CURRENCY in", values, "refundCurrency");
            return (Criteria) this;
        }

        public Criteria andRefundCurrencyNotIn(List<String> values) {
            addCriterion("REFUND_CURRENCY not in", values, "refundCurrency");
            return (Criteria) this;
        }

        public Criteria andRefundCurrencyBetween(String value1, String value2) {
            addCriterion("REFUND_CURRENCY between", value1, value2, "refundCurrency");
            return (Criteria) this;
        }

        public Criteria andRefundCurrencyNotBetween(String value1, String value2) {
            addCriterion("REFUND_CURRENCY not between", value1, value2, "refundCurrency");
            return (Criteria) this;
        }

        public Criteria andRefundAcctnoIsNull() {
            addCriterion("REFUND_ACCTNO is null");
            return (Criteria) this;
        }

        public Criteria andRefundAcctnoIsNotNull() {
            addCriterion("REFUND_ACCTNO is not null");
            return (Criteria) this;
        }

        public Criteria andRefundAcctnoEqualTo(String value) {
            addCriterion("REFUND_ACCTNO =", value, "refundAcctno");
            return (Criteria) this;
        }

        public Criteria andRefundAcctnoNotEqualTo(String value) {
            addCriterion("REFUND_ACCTNO <>", value, "refundAcctno");
            return (Criteria) this;
        }

        public Criteria andRefundAcctnoGreaterThan(String value) {
            addCriterion("REFUND_ACCTNO >", value, "refundAcctno");
            return (Criteria) this;
        }

        public Criteria andRefundAcctnoGreaterThanOrEqualTo(String value) {
            addCriterion("REFUND_ACCTNO >=", value, "refundAcctno");
            return (Criteria) this;
        }

        public Criteria andRefundAcctnoLessThan(String value) {
            addCriterion("REFUND_ACCTNO <", value, "refundAcctno");
            return (Criteria) this;
        }

        public Criteria andRefundAcctnoLessThanOrEqualTo(String value) {
            addCriterion("REFUND_ACCTNO <=", value, "refundAcctno");
            return (Criteria) this;
        }

        public Criteria andRefundAcctnoLike(String value) {
            addCriterion("REFUND_ACCTNO like", value, "refundAcctno");
            return (Criteria) this;
        }

        public Criteria andRefundAcctnoNotLike(String value) {
            addCriterion("REFUND_ACCTNO not like", value, "refundAcctno");
            return (Criteria) this;
        }

        public Criteria andRefundAcctnoIn(List<String> values) {
            addCriterion("REFUND_ACCTNO in", values, "refundAcctno");
            return (Criteria) this;
        }

        public Criteria andRefundAcctnoNotIn(List<String> values) {
            addCriterion("REFUND_ACCTNO not in", values, "refundAcctno");
            return (Criteria) this;
        }

        public Criteria andRefundAcctnoBetween(String value1, String value2) {
            addCriterion("REFUND_ACCTNO between", value1, value2, "refundAcctno");
            return (Criteria) this;
        }

        public Criteria andRefundAcctnoNotBetween(String value1, String value2) {
            addCriterion("REFUND_ACCTNO not between", value1, value2, "refundAcctno");
            return (Criteria) this;
        }

        public Criteria andRefundAcctnameIsNull() {
            addCriterion("REFUND_ACCTNAME is null");
            return (Criteria) this;
        }

        public Criteria andRefundAcctnameIsNotNull() {
            addCriterion("REFUND_ACCTNAME is not null");
            return (Criteria) this;
        }

        public Criteria andRefundAcctnameEqualTo(String value) {
            addCriterion("REFUND_ACCTNAME =", value, "refundAcctname");
            return (Criteria) this;
        }

        public Criteria andRefundAcctnameNotEqualTo(String value) {
            addCriterion("REFUND_ACCTNAME <>", value, "refundAcctname");
            return (Criteria) this;
        }

        public Criteria andRefundAcctnameGreaterThan(String value) {
            addCriterion("REFUND_ACCTNAME >", value, "refundAcctname");
            return (Criteria) this;
        }

        public Criteria andRefundAcctnameGreaterThanOrEqualTo(String value) {
            addCriterion("REFUND_ACCTNAME >=", value, "refundAcctname");
            return (Criteria) this;
        }

        public Criteria andRefundAcctnameLessThan(String value) {
            addCriterion("REFUND_ACCTNAME <", value, "refundAcctname");
            return (Criteria) this;
        }

        public Criteria andRefundAcctnameLessThanOrEqualTo(String value) {
            addCriterion("REFUND_ACCTNAME <=", value, "refundAcctname");
            return (Criteria) this;
        }

        public Criteria andRefundAcctnameLike(String value) {
            addCriterion("REFUND_ACCTNAME like", value, "refundAcctname");
            return (Criteria) this;
        }

        public Criteria andRefundAcctnameNotLike(String value) {
            addCriterion("REFUND_ACCTNAME not like", value, "refundAcctname");
            return (Criteria) this;
        }

        public Criteria andRefundAcctnameIn(List<String> values) {
            addCriterion("REFUND_ACCTNAME in", values, "refundAcctname");
            return (Criteria) this;
        }

        public Criteria andRefundAcctnameNotIn(List<String> values) {
            addCriterion("REFUND_ACCTNAME not in", values, "refundAcctname");
            return (Criteria) this;
        }

        public Criteria andRefundAcctnameBetween(String value1, String value2) {
            addCriterion("REFUND_ACCTNAME between", value1, value2, "refundAcctname");
            return (Criteria) this;
        }

        public Criteria andRefundAcctnameNotBetween(String value1, String value2) {
            addCriterion("REFUND_ACCTNAME not between", value1, value2, "refundAcctname");
            return (Criteria) this;
        }

        public Criteria andSourceIsNull() {
            addCriterion("SOURCE is null");
            return (Criteria) this;
        }

        public Criteria andSourceIsNotNull() {
            addCriterion("SOURCE is not null");
            return (Criteria) this;
        }

        public Criteria andSourceEqualTo(String value) {
            addCriterion("SOURCE =", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotEqualTo(String value) {
            addCriterion("SOURCE <>", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThan(String value) {
            addCriterion("SOURCE >", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThanOrEqualTo(String value) {
            addCriterion("SOURCE >=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThan(String value) {
            addCriterion("SOURCE <", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThanOrEqualTo(String value) {
            addCriterion("SOURCE <=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLike(String value) {
            addCriterion("SOURCE like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotLike(String value) {
            addCriterion("SOURCE not like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceIn(List<String> values) {
            addCriterion("SOURCE in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotIn(List<String> values) {
            addCriterion("SOURCE not in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceBetween(String value1, String value2) {
            addCriterion("SOURCE between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotBetween(String value1, String value2) {
            addCriterion("SOURCE not between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andChnlCodeIsNull() {
            addCriterion("CHNL_CODE is null");
            return (Criteria) this;
        }

        public Criteria andChnlCodeIsNotNull() {
            addCriterion("CHNL_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andChnlCodeEqualTo(String value) {
            addCriterion("CHNL_CODE =", value, "chnlCode");
            return (Criteria) this;
        }

        public Criteria andChnlCodeNotEqualTo(String value) {
            addCriterion("CHNL_CODE <>", value, "chnlCode");
            return (Criteria) this;
        }

        public Criteria andChnlCodeGreaterThan(String value) {
            addCriterion("CHNL_CODE >", value, "chnlCode");
            return (Criteria) this;
        }

        public Criteria andChnlCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CHNL_CODE >=", value, "chnlCode");
            return (Criteria) this;
        }

        public Criteria andChnlCodeLessThan(String value) {
            addCriterion("CHNL_CODE <", value, "chnlCode");
            return (Criteria) this;
        }

        public Criteria andChnlCodeLessThanOrEqualTo(String value) {
            addCriterion("CHNL_CODE <=", value, "chnlCode");
            return (Criteria) this;
        }

        public Criteria andChnlCodeLike(String value) {
            addCriterion("CHNL_CODE like", value, "chnlCode");
            return (Criteria) this;
        }

        public Criteria andChnlCodeNotLike(String value) {
            addCriterion("CHNL_CODE not like", value, "chnlCode");
            return (Criteria) this;
        }

        public Criteria andChnlCodeIn(List<String> values) {
            addCriterion("CHNL_CODE in", values, "chnlCode");
            return (Criteria) this;
        }

        public Criteria andChnlCodeNotIn(List<String> values) {
            addCriterion("CHNL_CODE not in", values, "chnlCode");
            return (Criteria) this;
        }

        public Criteria andChnlCodeBetween(String value1, String value2) {
            addCriterion("CHNL_CODE between", value1, value2, "chnlCode");
            return (Criteria) this;
        }

        public Criteria andChnlCodeNotBetween(String value1, String value2) {
            addCriterion("CHNL_CODE not between", value1, value2, "chnlCode");
            return (Criteria) this;
        }

        public Criteria andBankRetCodeIsNull() {
            addCriterion("BANK_RET_CODE is null");
            return (Criteria) this;
        }

        public Criteria andBankRetCodeIsNotNull() {
            addCriterion("BANK_RET_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andBankRetCodeEqualTo(String value) {
            addCriterion("BANK_RET_CODE =", value, "bankRetCode");
            return (Criteria) this;
        }

        public Criteria andBankRetCodeNotEqualTo(String value) {
            addCriterion("BANK_RET_CODE <>", value, "bankRetCode");
            return (Criteria) this;
        }

        public Criteria andBankRetCodeGreaterThan(String value) {
            addCriterion("BANK_RET_CODE >", value, "bankRetCode");
            return (Criteria) this;
        }

        public Criteria andBankRetCodeGreaterThanOrEqualTo(String value) {
            addCriterion("BANK_RET_CODE >=", value, "bankRetCode");
            return (Criteria) this;
        }

        public Criteria andBankRetCodeLessThan(String value) {
            addCriterion("BANK_RET_CODE <", value, "bankRetCode");
            return (Criteria) this;
        }

        public Criteria andBankRetCodeLessThanOrEqualTo(String value) {
            addCriterion("BANK_RET_CODE <=", value, "bankRetCode");
            return (Criteria) this;
        }

        public Criteria andBankRetCodeLike(String value) {
            addCriterion("BANK_RET_CODE like", value, "bankRetCode");
            return (Criteria) this;
        }

        public Criteria andBankRetCodeNotLike(String value) {
            addCriterion("BANK_RET_CODE not like", value, "bankRetCode");
            return (Criteria) this;
        }

        public Criteria andBankRetCodeIn(List<String> values) {
            addCriterion("BANK_RET_CODE in", values, "bankRetCode");
            return (Criteria) this;
        }

        public Criteria andBankRetCodeNotIn(List<String> values) {
            addCriterion("BANK_RET_CODE not in", values, "bankRetCode");
            return (Criteria) this;
        }

        public Criteria andBankRetCodeBetween(String value1, String value2) {
            addCriterion("BANK_RET_CODE between", value1, value2, "bankRetCode");
            return (Criteria) this;
        }

        public Criteria andBankRetCodeNotBetween(String value1, String value2) {
            addCriterion("BANK_RET_CODE not between", value1, value2, "bankRetCode");
            return (Criteria) this;
        }

        public Criteria andBankRetMsgIsNull() {
            addCriterion("BANK_RET_MSG is null");
            return (Criteria) this;
        }

        public Criteria andBankRetMsgIsNotNull() {
            addCriterion("BANK_RET_MSG is not null");
            return (Criteria) this;
        }

        public Criteria andBankRetMsgEqualTo(String value) {
            addCriterion("BANK_RET_MSG =", value, "bankRetMsg");
            return (Criteria) this;
        }

        public Criteria andBankRetMsgNotEqualTo(String value) {
            addCriterion("BANK_RET_MSG <>", value, "bankRetMsg");
            return (Criteria) this;
        }

        public Criteria andBankRetMsgGreaterThan(String value) {
            addCriterion("BANK_RET_MSG >", value, "bankRetMsg");
            return (Criteria) this;
        }

        public Criteria andBankRetMsgGreaterThanOrEqualTo(String value) {
            addCriterion("BANK_RET_MSG >=", value, "bankRetMsg");
            return (Criteria) this;
        }

        public Criteria andBankRetMsgLessThan(String value) {
            addCriterion("BANK_RET_MSG <", value, "bankRetMsg");
            return (Criteria) this;
        }

        public Criteria andBankRetMsgLessThanOrEqualTo(String value) {
            addCriterion("BANK_RET_MSG <=", value, "bankRetMsg");
            return (Criteria) this;
        }

        public Criteria andBankRetMsgLike(String value) {
            addCriterion("BANK_RET_MSG like", value, "bankRetMsg");
            return (Criteria) this;
        }

        public Criteria andBankRetMsgNotLike(String value) {
            addCriterion("BANK_RET_MSG not like", value, "bankRetMsg");
            return (Criteria) this;
        }

        public Criteria andBankRetMsgIn(List<String> values) {
            addCriterion("BANK_RET_MSG in", values, "bankRetMsg");
            return (Criteria) this;
        }

        public Criteria andBankRetMsgNotIn(List<String> values) {
            addCriterion("BANK_RET_MSG not in", values, "bankRetMsg");
            return (Criteria) this;
        }

        public Criteria andBankRetMsgBetween(String value1, String value2) {
            addCriterion("BANK_RET_MSG between", value1, value2, "bankRetMsg");
            return (Criteria) this;
        }

        public Criteria andBankRetMsgNotBetween(String value1, String value2) {
            addCriterion("BANK_RET_MSG not between", value1, value2, "bankRetMsg");
            return (Criteria) this;
        }

        public Criteria andBankSerialnoIsNull() {
            addCriterion("BANK_SERIALNO is null");
            return (Criteria) this;
        }

        public Criteria andBankSerialnoIsNotNull() {
            addCriterion("BANK_SERIALNO is not null");
            return (Criteria) this;
        }

        public Criteria andBankSerialnoEqualTo(String value) {
            addCriterion("BANK_SERIALNO =", value, "bankSerialno");
            return (Criteria) this;
        }

        public Criteria andBankSerialnoNotEqualTo(String value) {
            addCriterion("BANK_SERIALNO <>", value, "bankSerialno");
            return (Criteria) this;
        }

        public Criteria andBankSerialnoGreaterThan(String value) {
            addCriterion("BANK_SERIALNO >", value, "bankSerialno");
            return (Criteria) this;
        }

        public Criteria andBankSerialnoGreaterThanOrEqualTo(String value) {
            addCriterion("BANK_SERIALNO >=", value, "bankSerialno");
            return (Criteria) this;
        }

        public Criteria andBankSerialnoLessThan(String value) {
            addCriterion("BANK_SERIALNO <", value, "bankSerialno");
            return (Criteria) this;
        }

        public Criteria andBankSerialnoLessThanOrEqualTo(String value) {
            addCriterion("BANK_SERIALNO <=", value, "bankSerialno");
            return (Criteria) this;
        }

        public Criteria andBankSerialnoLike(String value) {
            addCriterion("BANK_SERIALNO like", value, "bankSerialno");
            return (Criteria) this;
        }

        public Criteria andBankSerialnoNotLike(String value) {
            addCriterion("BANK_SERIALNO not like", value, "bankSerialno");
            return (Criteria) this;
        }

        public Criteria andBankSerialnoIn(List<String> values) {
            addCriterion("BANK_SERIALNO in", values, "bankSerialno");
            return (Criteria) this;
        }

        public Criteria andBankSerialnoNotIn(List<String> values) {
            addCriterion("BANK_SERIALNO not in", values, "bankSerialno");
            return (Criteria) this;
        }

        public Criteria andBankSerialnoBetween(String value1, String value2) {
            addCriterion("BANK_SERIALNO between", value1, value2, "bankSerialno");
            return (Criteria) this;
        }

        public Criteria andBankSerialnoNotBetween(String value1, String value2) {
            addCriterion("BANK_SERIALNO not between", value1, value2, "bankSerialno");
            return (Criteria) this;
        }

        public Criteria andSettleDateIsNull() {
            addCriterion("SETTLE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andSettleDateIsNotNull() {
            addCriterion("SETTLE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andSettleDateEqualTo(String value) {
            addCriterion("SETTLE_DATE =", value, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateNotEqualTo(String value) {
            addCriterion("SETTLE_DATE <>", value, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateGreaterThan(String value) {
            addCriterion("SETTLE_DATE >", value, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateGreaterThanOrEqualTo(String value) {
            addCriterion("SETTLE_DATE >=", value, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateLessThan(String value) {
            addCriterion("SETTLE_DATE <", value, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateLessThanOrEqualTo(String value) {
            addCriterion("SETTLE_DATE <=", value, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateLike(String value) {
            addCriterion("SETTLE_DATE like", value, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateNotLike(String value) {
            addCriterion("SETTLE_DATE not like", value, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateIn(List<String> values) {
            addCriterion("SETTLE_DATE in", values, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateNotIn(List<String> values) {
            addCriterion("SETTLE_DATE not in", values, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateBetween(String value1, String value2) {
            addCriterion("SETTLE_DATE between", value1, value2, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateNotBetween(String value1, String value2) {
            addCriterion("SETTLE_DATE not between", value1, value2, "settleDate");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("MODIFY_TIME is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("MODIFY_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("MODIFY_TIME =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("MODIFY_TIME <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("MODIFY_TIME >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFY_TIME >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("MODIFY_TIME <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("MODIFY_TIME <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("MODIFY_TIME in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("MODIFY_TIME not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("MODIFY_TIME between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("MODIFY_TIME not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andOidRefundnoIsNull() {
            addCriterion("OID_REFUNDNO is null");
            return (Criteria) this;
        }

        public Criteria andOidRefundnoIsNotNull() {
            addCriterion("OID_REFUNDNO is not null");
            return (Criteria) this;
        }

        public Criteria andOidRefundnoEqualTo(Long value) {
            addCriterion("OID_REFUNDNO =", value, "oidRefundno");
            return (Criteria) this;
        }

        public Criteria andOidRefundnoNotEqualTo(Long value) {
            addCriterion("OID_REFUNDNO <>", value, "oidRefundno");
            return (Criteria) this;
        }

        public Criteria andOidRefundnoGreaterThan(Long value) {
            addCriterion("OID_REFUNDNO >", value, "oidRefundno");
            return (Criteria) this;
        }

        public Criteria andOidRefundnoGreaterThanOrEqualTo(Long value) {
            addCriterion("OID_REFUNDNO >=", value, "oidRefundno");
            return (Criteria) this;
        }

        public Criteria andOidRefundnoLessThan(Long value) {
            addCriterion("OID_REFUNDNO <", value, "oidRefundno");
            return (Criteria) this;
        }

        public Criteria andOidRefundnoLessThanOrEqualTo(Long value) {
            addCriterion("OID_REFUNDNO <=", value, "oidRefundno");
            return (Criteria) this;
        }

        public Criteria andOidRefundnoIn(List<Long> values) {
            addCriterion("OID_REFUNDNO in", values, "oidRefundno");
            return (Criteria) this;
        }

        public Criteria andOidRefundnoNotIn(List<Long> values) {
            addCriterion("OID_REFUNDNO not in", values, "oidRefundno");
            return (Criteria) this;
        }

        public Criteria andOidRefundnoBetween(Long value1, Long value2) {
            addCriterion("OID_REFUNDNO between", value1, value2, "oidRefundno");
            return (Criteria) this;
        }

        public Criteria andOidRefundnoNotBetween(Long value1, Long value2) {
            addCriterion("OID_REFUNDNO not between", value1, value2, "oidRefundno");
            return (Criteria) this;
        }

        public Criteria andYtHasSerialnoIsNull() {
            addCriterion("YT_HAS_SERIALNO is null");
            return (Criteria) this;
        }

        public Criteria andYtHasSerialnoIsNotNull() {
            addCriterion("YT_HAS_SERIALNO is not null");
            return (Criteria) this;
        }

        public Criteria andYtHasSerialnoEqualTo(String value) {
            addCriterion("YT_HAS_SERIALNO =", value, "ytHasSerialno");
            return (Criteria) this;
        }

        public Criteria andYtHasSerialnoNotEqualTo(String value) {
            addCriterion("YT_HAS_SERIALNO <>", value, "ytHasSerialno");
            return (Criteria) this;
        }

        public Criteria andYtHasSerialnoGreaterThan(String value) {
            addCriterion("YT_HAS_SERIALNO >", value, "ytHasSerialno");
            return (Criteria) this;
        }

        public Criteria andYtHasSerialnoGreaterThanOrEqualTo(String value) {
            addCriterion("YT_HAS_SERIALNO >=", value, "ytHasSerialno");
            return (Criteria) this;
        }

        public Criteria andYtHasSerialnoLessThan(String value) {
            addCriterion("YT_HAS_SERIALNO <", value, "ytHasSerialno");
            return (Criteria) this;
        }

        public Criteria andYtHasSerialnoLessThanOrEqualTo(String value) {
            addCriterion("YT_HAS_SERIALNO <=", value, "ytHasSerialno");
            return (Criteria) this;
        }

        public Criteria andYtHasSerialnoLike(String value) {
            addCriterion("YT_HAS_SERIALNO like", value, "ytHasSerialno");
            return (Criteria) this;
        }

        public Criteria andYtHasSerialnoNotLike(String value) {
            addCriterion("YT_HAS_SERIALNO not like", value, "ytHasSerialno");
            return (Criteria) this;
        }

        public Criteria andYtHasSerialnoIn(List<String> values) {
            addCriterion("YT_HAS_SERIALNO in", values, "ytHasSerialno");
            return (Criteria) this;
        }

        public Criteria andYtHasSerialnoNotIn(List<String> values) {
            addCriterion("YT_HAS_SERIALNO not in", values, "ytHasSerialno");
            return (Criteria) this;
        }

        public Criteria andYtHasSerialnoBetween(String value1, String value2) {
            addCriterion("YT_HAS_SERIALNO between", value1, value2, "ytHasSerialno");
            return (Criteria) this;
        }

        public Criteria andYtHasSerialnoNotBetween(String value1, String value2) {
            addCriterion("YT_HAS_SERIALNO not between", value1, value2, "ytHasSerialno");
            return (Criteria) this;
        }

        public Criteria andProcessTypeIsNull() {
            addCriterion("PROCESS_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andProcessTypeIsNotNull() {
            addCriterion("PROCESS_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andProcessTypeEqualTo(String value) {
            addCriterion("PROCESS_TYPE =", value, "processType");
            return (Criteria) this;
        }

        public Criteria andProcessTypeNotEqualTo(String value) {
            addCriterion("PROCESS_TYPE <>", value, "processType");
            return (Criteria) this;
        }

        public Criteria andProcessTypeGreaterThan(String value) {
            addCriterion("PROCESS_TYPE >", value, "processType");
            return (Criteria) this;
        }

        public Criteria andProcessTypeGreaterThanOrEqualTo(String value) {
            addCriterion("PROCESS_TYPE >=", value, "processType");
            return (Criteria) this;
        }

        public Criteria andProcessTypeLessThan(String value) {
            addCriterion("PROCESS_TYPE <", value, "processType");
            return (Criteria) this;
        }

        public Criteria andProcessTypeLessThanOrEqualTo(String value) {
            addCriterion("PROCESS_TYPE <=", value, "processType");
            return (Criteria) this;
        }

        public Criteria andProcessTypeLike(String value) {
            addCriterion("PROCESS_TYPE like", value, "processType");
            return (Criteria) this;
        }

        public Criteria andProcessTypeNotLike(String value) {
            addCriterion("PROCESS_TYPE not like", value, "processType");
            return (Criteria) this;
        }

        public Criteria andProcessTypeIn(List<String> values) {
            addCriterion("PROCESS_TYPE in", values, "processType");
            return (Criteria) this;
        }

        public Criteria andProcessTypeNotIn(List<String> values) {
            addCriterion("PROCESS_TYPE not in", values, "processType");
            return (Criteria) this;
        }

        public Criteria andProcessTypeBetween(String value1, String value2) {
            addCriterion("PROCESS_TYPE between", value1, value2, "processType");
            return (Criteria) this;
        }

        public Criteria andProcessTypeNotBetween(String value1, String value2) {
            addCriterion("PROCESS_TYPE not between", value1, value2, "processType");
            return (Criteria) this;
        }

        public Criteria andWithdrawNoIsNull() {
            addCriterion("WITHDRAW_NO is null");
            return (Criteria) this;
        }

        public Criteria andWithdrawNoIsNotNull() {
            addCriterion("WITHDRAW_NO is not null");
            return (Criteria) this;
        }

        public Criteria andWithdrawNoEqualTo(Long value) {
            addCriterion("WITHDRAW_NO =", value, "withdrawNo");
            return (Criteria) this;
        }

        public Criteria andWithdrawNoNotEqualTo(Long value) {
            addCriterion("WITHDRAW_NO <>", value, "withdrawNo");
            return (Criteria) this;
        }

        public Criteria andWithdrawNoGreaterThan(Long value) {
            addCriterion("WITHDRAW_NO >", value, "withdrawNo");
            return (Criteria) this;
        }

        public Criteria andWithdrawNoGreaterThanOrEqualTo(Long value) {
            addCriterion("WITHDRAW_NO >=", value, "withdrawNo");
            return (Criteria) this;
        }

        public Criteria andWithdrawNoLessThan(Long value) {
            addCriterion("WITHDRAW_NO <", value, "withdrawNo");
            return (Criteria) this;
        }

        public Criteria andWithdrawNoLessThanOrEqualTo(Long value) {
            addCriterion("WITHDRAW_NO <=", value, "withdrawNo");
            return (Criteria) this;
        }

        public Criteria andWithdrawNoIn(List<Long> values) {
            addCriterion("WITHDRAW_NO in", values, "withdrawNo");
            return (Criteria) this;
        }

        public Criteria andWithdrawNoNotIn(List<Long> values) {
            addCriterion("WITHDRAW_NO not in", values, "withdrawNo");
            return (Criteria) this;
        }

        public Criteria andWithdrawNoBetween(Long value1, Long value2) {
            addCriterion("WITHDRAW_NO between", value1, value2, "withdrawNo");
            return (Criteria) this;
        }

        public Criteria andWithdrawNoNotBetween(Long value1, Long value2) {
            addCriterion("WITHDRAW_NO not between", value1, value2, "withdrawNo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_PAY_FIN_REFUND
     *
     * @mbg.generated do_not_delete_during_merge Wed Jul 18 14:21:44 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_PAY_FIN_REFUND
     *
     * @mbg.generated Wed Jul 18 14:21:44 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}