package com.chris.demo.core.auto;

import com.alibaba.fastjson.JSONObject;

import java.util.Date;

public class SalarySummary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SALARY_SUMMARY.summary_id
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    private String summaryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SALARY_SUMMARY.unique_id
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    private String uniqueId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SALARY_SUMMARY.oid_partner
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    private String oidPartner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SALARY_SUMMARY.enterprise_name
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    private String enterpriseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SALARY_SUMMARY.co_enterprise_id
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    private String coEnterpriseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SALARY_SUMMARY.summary_name
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    private String summaryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SALARY_SUMMARY.grant_month
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    private String grantMonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SALARY_SUMMARY.summary_num
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    private Integer summaryNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SALARY_SUMMARY.summary_amount
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    private Long summaryAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SALARY_SUMMARY.grant_state
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    private String grantState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SALARY_SUMMARY.audit_state
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    private String auditState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SALARY_SUMMARY.success_sum
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    private Short successSum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SALARY_SUMMARY.success_amount
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    private Long successAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SALARY_SUMMARY.fail_sum
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    private Short failSum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SALARY_SUMMARY.fail_amount
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    private Long failAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SALARY_SUMMARY.remit_sum
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    private Short remitSum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SALARY_SUMMARY.remit_amount
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    private Long remitAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SALARY_SUMMARY.form_creater
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    private String formCreater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SALARY_SUMMARY.grant_auditor
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    private String grantAuditor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SALARY_SUMMARY.remark
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SALARY_SUMMARY.salary_bill_title
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    private JSONObject salaryBillTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SALARY_SUMMARY.bill_send_flag
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    private String billSendFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SALARY_SUMMARY.create_time
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SALARY_SUMMARY.update_time
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SALARY_SUMMARY.str1
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    private String str1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SALARY_SUMMARY.summary_file_path
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    private String summaryFilePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SALARY_SUMMARY.purpose
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    private String purpose;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SALARY_SUMMARY.summary_file_md5
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    private String summaryFileMd5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SALARY_SUMMARY.reject_reason
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    private String rejectReason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SALARY_SUMMARY.summary_id
     *
     * @return the value of TB_SALARY_SUMMARY.summary_id
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public String getSummaryId() {
        return summaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SALARY_SUMMARY.summary_id
     *
     * @param summaryId the value for TB_SALARY_SUMMARY.summary_id
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public void setSummaryId(String summaryId) {
        this.summaryId = summaryId == null ? null : summaryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SALARY_SUMMARY.unique_id
     *
     * @return the value of TB_SALARY_SUMMARY.unique_id
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public String getUniqueId() {
        return uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SALARY_SUMMARY.unique_id
     *
     * @param uniqueId the value for TB_SALARY_SUMMARY.unique_id
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId == null ? null : uniqueId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SALARY_SUMMARY.oid_partner
     *
     * @return the value of TB_SALARY_SUMMARY.oid_partner
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public String getOidPartner() {
        return oidPartner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SALARY_SUMMARY.oid_partner
     *
     * @param oidPartner the value for TB_SALARY_SUMMARY.oid_partner
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public void setOidPartner(String oidPartner) {
        this.oidPartner = oidPartner == null ? null : oidPartner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SALARY_SUMMARY.enterprise_name
     *
     * @return the value of TB_SALARY_SUMMARY.enterprise_name
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public String getEnterpriseName() {
        return enterpriseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SALARY_SUMMARY.enterprise_name
     *
     * @param enterpriseName the value for TB_SALARY_SUMMARY.enterprise_name
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public void setEnterpriseName(String enterpriseName) {
        this.enterpriseName = enterpriseName == null ? null : enterpriseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SALARY_SUMMARY.co_enterprise_id
     *
     * @return the value of TB_SALARY_SUMMARY.co_enterprise_id
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public String getCoEnterpriseId() {
        return coEnterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SALARY_SUMMARY.co_enterprise_id
     *
     * @param coEnterpriseId the value for TB_SALARY_SUMMARY.co_enterprise_id
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public void setCoEnterpriseId(String coEnterpriseId) {
        this.coEnterpriseId = coEnterpriseId == null ? null : coEnterpriseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SALARY_SUMMARY.summary_name
     *
     * @return the value of TB_SALARY_SUMMARY.summary_name
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public String getSummaryName() {
        return summaryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SALARY_SUMMARY.summary_name
     *
     * @param summaryName the value for TB_SALARY_SUMMARY.summary_name
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public void setSummaryName(String summaryName) {
        this.summaryName = summaryName == null ? null : summaryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SALARY_SUMMARY.grant_month
     *
     * @return the value of TB_SALARY_SUMMARY.grant_month
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public String getGrantMonth() {
        return grantMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SALARY_SUMMARY.grant_month
     *
     * @param grantMonth the value for TB_SALARY_SUMMARY.grant_month
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public void setGrantMonth(String grantMonth) {
        this.grantMonth = grantMonth == null ? null : grantMonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SALARY_SUMMARY.summary_num
     *
     * @return the value of TB_SALARY_SUMMARY.summary_num
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public Integer getSummaryNum() {
        return summaryNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SALARY_SUMMARY.summary_num
     *
     * @param summaryNum the value for TB_SALARY_SUMMARY.summary_num
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public void setSummaryNum(Integer summaryNum) {
        this.summaryNum = summaryNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SALARY_SUMMARY.summary_amount
     *
     * @return the value of TB_SALARY_SUMMARY.summary_amount
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public Long getSummaryAmount() {
        return summaryAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SALARY_SUMMARY.summary_amount
     *
     * @param summaryAmount the value for TB_SALARY_SUMMARY.summary_amount
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public void setSummaryAmount(Long summaryAmount) {
        this.summaryAmount = summaryAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SALARY_SUMMARY.grant_state
     *
     * @return the value of TB_SALARY_SUMMARY.grant_state
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public String getGrantState() {
        return grantState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SALARY_SUMMARY.grant_state
     *
     * @param grantState the value for TB_SALARY_SUMMARY.grant_state
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public void setGrantState(String grantState) {
        this.grantState = grantState == null ? null : grantState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SALARY_SUMMARY.audit_state
     *
     * @return the value of TB_SALARY_SUMMARY.audit_state
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public String getAuditState() {
        return auditState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SALARY_SUMMARY.audit_state
     *
     * @param auditState the value for TB_SALARY_SUMMARY.audit_state
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public void setAuditState(String auditState) {
        this.auditState = auditState == null ? null : auditState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SALARY_SUMMARY.success_sum
     *
     * @return the value of TB_SALARY_SUMMARY.success_sum
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public Short getSuccessSum() {
        return successSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SALARY_SUMMARY.success_sum
     *
     * @param successSum the value for TB_SALARY_SUMMARY.success_sum
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public void setSuccessSum(Short successSum) {
        this.successSum = successSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SALARY_SUMMARY.success_amount
     *
     * @return the value of TB_SALARY_SUMMARY.success_amount
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public Long getSuccessAmount() {
        return successAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SALARY_SUMMARY.success_amount
     *
     * @param successAmount the value for TB_SALARY_SUMMARY.success_amount
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public void setSuccessAmount(Long successAmount) {
        this.successAmount = successAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SALARY_SUMMARY.fail_sum
     *
     * @return the value of TB_SALARY_SUMMARY.fail_sum
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public Short getFailSum() {
        return failSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SALARY_SUMMARY.fail_sum
     *
     * @param failSum the value for TB_SALARY_SUMMARY.fail_sum
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public void setFailSum(Short failSum) {
        this.failSum = failSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SALARY_SUMMARY.fail_amount
     *
     * @return the value of TB_SALARY_SUMMARY.fail_amount
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public Long getFailAmount() {
        return failAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SALARY_SUMMARY.fail_amount
     *
     * @param failAmount the value for TB_SALARY_SUMMARY.fail_amount
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public void setFailAmount(Long failAmount) {
        this.failAmount = failAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SALARY_SUMMARY.remit_sum
     *
     * @return the value of TB_SALARY_SUMMARY.remit_sum
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public Short getRemitSum() {
        return remitSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SALARY_SUMMARY.remit_sum
     *
     * @param remitSum the value for TB_SALARY_SUMMARY.remit_sum
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public void setRemitSum(Short remitSum) {
        this.remitSum = remitSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SALARY_SUMMARY.remit_amount
     *
     * @return the value of TB_SALARY_SUMMARY.remit_amount
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public Long getRemitAmount() {
        return remitAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SALARY_SUMMARY.remit_amount
     *
     * @param remitAmount the value for TB_SALARY_SUMMARY.remit_amount
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public void setRemitAmount(Long remitAmount) {
        this.remitAmount = remitAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SALARY_SUMMARY.form_creater
     *
     * @return the value of TB_SALARY_SUMMARY.form_creater
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public String getFormCreater() {
        return formCreater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SALARY_SUMMARY.form_creater
     *
     * @param formCreater the value for TB_SALARY_SUMMARY.form_creater
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public void setFormCreater(String formCreater) {
        this.formCreater = formCreater == null ? null : formCreater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SALARY_SUMMARY.grant_auditor
     *
     * @return the value of TB_SALARY_SUMMARY.grant_auditor
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public String getGrantAuditor() {
        return grantAuditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SALARY_SUMMARY.grant_auditor
     *
     * @param grantAuditor the value for TB_SALARY_SUMMARY.grant_auditor
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public void setGrantAuditor(String grantAuditor) {
        this.grantAuditor = grantAuditor == null ? null : grantAuditor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SALARY_SUMMARY.remark
     *
     * @return the value of TB_SALARY_SUMMARY.remark
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SALARY_SUMMARY.remark
     *
     * @param remark the value for TB_SALARY_SUMMARY.remark
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SALARY_SUMMARY.salary_bill_title
     *
     * @return the value of TB_SALARY_SUMMARY.salary_bill_title
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public JSONObject getSalaryBillTitle() {
        return salaryBillTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SALARY_SUMMARY.salary_bill_title
     *
     * @param salaryBillTitle the value for TB_SALARY_SUMMARY.salary_bill_title
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public void setSalaryBillTitle(JSONObject salaryBillTitle) {
        this.salaryBillTitle = salaryBillTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SALARY_SUMMARY.bill_send_flag
     *
     * @return the value of TB_SALARY_SUMMARY.bill_send_flag
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public String getBillSendFlag() {
        return billSendFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SALARY_SUMMARY.bill_send_flag
     *
     * @param billSendFlag the value for TB_SALARY_SUMMARY.bill_send_flag
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public void setBillSendFlag(String billSendFlag) {
        this.billSendFlag = billSendFlag == null ? null : billSendFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SALARY_SUMMARY.create_time
     *
     * @return the value of TB_SALARY_SUMMARY.create_time
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SALARY_SUMMARY.create_time
     *
     * @param createTime the value for TB_SALARY_SUMMARY.create_time
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SALARY_SUMMARY.update_time
     *
     * @return the value of TB_SALARY_SUMMARY.update_time
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SALARY_SUMMARY.update_time
     *
     * @param updateTime the value for TB_SALARY_SUMMARY.update_time
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SALARY_SUMMARY.str1
     *
     * @return the value of TB_SALARY_SUMMARY.str1
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public String getStr1() {
        return str1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SALARY_SUMMARY.str1
     *
     * @param str1 the value for TB_SALARY_SUMMARY.str1
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public void setStr1(String str1) {
        this.str1 = str1 == null ? null : str1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SALARY_SUMMARY.summary_file_path
     *
     * @return the value of TB_SALARY_SUMMARY.summary_file_path
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public String getSummaryFilePath() {
        return summaryFilePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SALARY_SUMMARY.summary_file_path
     *
     * @param summaryFilePath the value for TB_SALARY_SUMMARY.summary_file_path
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public void setSummaryFilePath(String summaryFilePath) {
        this.summaryFilePath = summaryFilePath == null ? null : summaryFilePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SALARY_SUMMARY.purpose
     *
     * @return the value of TB_SALARY_SUMMARY.purpose
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public String getPurpose() {
        return purpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SALARY_SUMMARY.purpose
     *
     * @param purpose the value for TB_SALARY_SUMMARY.purpose
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public void setPurpose(String purpose) {
        this.purpose = purpose == null ? null : purpose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SALARY_SUMMARY.summary_file_md5
     *
     * @return the value of TB_SALARY_SUMMARY.summary_file_md5
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public String getSummaryFileMd5() {
        return summaryFileMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SALARY_SUMMARY.summary_file_md5
     *
     * @param summaryFileMd5 the value for TB_SALARY_SUMMARY.summary_file_md5
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public void setSummaryFileMd5(String summaryFileMd5) {
        this.summaryFileMd5 = summaryFileMd5 == null ? null : summaryFileMd5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SALARY_SUMMARY.reject_reason
     *
     * @return the value of TB_SALARY_SUMMARY.reject_reason
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public String getRejectReason() {
        return rejectReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SALARY_SUMMARY.reject_reason
     *
     * @param rejectReason the value for TB_SALARY_SUMMARY.reject_reason
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public void setRejectReason(String rejectReason) {
        this.rejectReason = rejectReason == null ? null : rejectReason.trim();
    }
}