package com.chris.demo.core.auto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SalarySummaryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_SALARY_SUMMARY
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_SALARY_SUMMARY
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_SALARY_SUMMARY
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SALARY_SUMMARY
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public SalarySummaryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SALARY_SUMMARY
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SALARY_SUMMARY
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SALARY_SUMMARY
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SALARY_SUMMARY
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SALARY_SUMMARY
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SALARY_SUMMARY
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SALARY_SUMMARY
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SALARY_SUMMARY
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SALARY_SUMMARY
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SALARY_SUMMARY
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_SALARY_SUMMARY
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSummaryIdIsNull() {
            addCriterion("summary_id is null");
            return (Criteria) this;
        }

        public Criteria andSummaryIdIsNotNull() {
            addCriterion("summary_id is not null");
            return (Criteria) this;
        }

        public Criteria andSummaryIdEqualTo(String value) {
            addCriterion("summary_id =", value, "summaryId");
            return (Criteria) this;
        }

        public Criteria andSummaryIdNotEqualTo(String value) {
            addCriterion("summary_id <>", value, "summaryId");
            return (Criteria) this;
        }

        public Criteria andSummaryIdGreaterThan(String value) {
            addCriterion("summary_id >", value, "summaryId");
            return (Criteria) this;
        }

        public Criteria andSummaryIdGreaterThanOrEqualTo(String value) {
            addCriterion("summary_id >=", value, "summaryId");
            return (Criteria) this;
        }

        public Criteria andSummaryIdLessThan(String value) {
            addCriterion("summary_id <", value, "summaryId");
            return (Criteria) this;
        }

        public Criteria andSummaryIdLessThanOrEqualTo(String value) {
            addCriterion("summary_id <=", value, "summaryId");
            return (Criteria) this;
        }

        public Criteria andSummaryIdLike(String value) {
            addCriterion("summary_id like", value, "summaryId");
            return (Criteria) this;
        }

        public Criteria andSummaryIdNotLike(String value) {
            addCriterion("summary_id not like", value, "summaryId");
            return (Criteria) this;
        }

        public Criteria andSummaryIdIn(List<String> values) {
            addCriterion("summary_id in", values, "summaryId");
            return (Criteria) this;
        }

        public Criteria andSummaryIdNotIn(List<String> values) {
            addCriterion("summary_id not in", values, "summaryId");
            return (Criteria) this;
        }

        public Criteria andSummaryIdBetween(String value1, String value2) {
            addCriterion("summary_id between", value1, value2, "summaryId");
            return (Criteria) this;
        }

        public Criteria andSummaryIdNotBetween(String value1, String value2) {
            addCriterion("summary_id not between", value1, value2, "summaryId");
            return (Criteria) this;
        }

        public Criteria andUniqueIdIsNull() {
            addCriterion("unique_id is null");
            return (Criteria) this;
        }

        public Criteria andUniqueIdIsNotNull() {
            addCriterion("unique_id is not null");
            return (Criteria) this;
        }

        public Criteria andUniqueIdEqualTo(String value) {
            addCriterion("unique_id =", value, "uniqueId");
            return (Criteria) this;
        }

        public Criteria andUniqueIdNotEqualTo(String value) {
            addCriterion("unique_id <>", value, "uniqueId");
            return (Criteria) this;
        }

        public Criteria andUniqueIdGreaterThan(String value) {
            addCriterion("unique_id >", value, "uniqueId");
            return (Criteria) this;
        }

        public Criteria andUniqueIdGreaterThanOrEqualTo(String value) {
            addCriterion("unique_id >=", value, "uniqueId");
            return (Criteria) this;
        }

        public Criteria andUniqueIdLessThan(String value) {
            addCriterion("unique_id <", value, "uniqueId");
            return (Criteria) this;
        }

        public Criteria andUniqueIdLessThanOrEqualTo(String value) {
            addCriterion("unique_id <=", value, "uniqueId");
            return (Criteria) this;
        }

        public Criteria andUniqueIdLike(String value) {
            addCriterion("unique_id like", value, "uniqueId");
            return (Criteria) this;
        }

        public Criteria andUniqueIdNotLike(String value) {
            addCriterion("unique_id not like", value, "uniqueId");
            return (Criteria) this;
        }

        public Criteria andUniqueIdIn(List<String> values) {
            addCriterion("unique_id in", values, "uniqueId");
            return (Criteria) this;
        }

        public Criteria andUniqueIdNotIn(List<String> values) {
            addCriterion("unique_id not in", values, "uniqueId");
            return (Criteria) this;
        }

        public Criteria andUniqueIdBetween(String value1, String value2) {
            addCriterion("unique_id between", value1, value2, "uniqueId");
            return (Criteria) this;
        }

        public Criteria andUniqueIdNotBetween(String value1, String value2) {
            addCriterion("unique_id not between", value1, value2, "uniqueId");
            return (Criteria) this;
        }

        public Criteria andOidPartnerIsNull() {
            addCriterion("oid_partner is null");
            return (Criteria) this;
        }

        public Criteria andOidPartnerIsNotNull() {
            addCriterion("oid_partner is not null");
            return (Criteria) this;
        }

        public Criteria andOidPartnerEqualTo(String value) {
            addCriterion("oid_partner =", value, "oidPartner");
            return (Criteria) this;
        }

        public Criteria andOidPartnerNotEqualTo(String value) {
            addCriterion("oid_partner <>", value, "oidPartner");
            return (Criteria) this;
        }

        public Criteria andOidPartnerGreaterThan(String value) {
            addCriterion("oid_partner >", value, "oidPartner");
            return (Criteria) this;
        }

        public Criteria andOidPartnerGreaterThanOrEqualTo(String value) {
            addCriterion("oid_partner >=", value, "oidPartner");
            return (Criteria) this;
        }

        public Criteria andOidPartnerLessThan(String value) {
            addCriterion("oid_partner <", value, "oidPartner");
            return (Criteria) this;
        }

        public Criteria andOidPartnerLessThanOrEqualTo(String value) {
            addCriterion("oid_partner <=", value, "oidPartner");
            return (Criteria) this;
        }

        public Criteria andOidPartnerLike(String value) {
            addCriterion("oid_partner like", value, "oidPartner");
            return (Criteria) this;
        }

        public Criteria andOidPartnerNotLike(String value) {
            addCriterion("oid_partner not like", value, "oidPartner");
            return (Criteria) this;
        }

        public Criteria andOidPartnerIn(List<String> values) {
            addCriterion("oid_partner in", values, "oidPartner");
            return (Criteria) this;
        }

        public Criteria andOidPartnerNotIn(List<String> values) {
            addCriterion("oid_partner not in", values, "oidPartner");
            return (Criteria) this;
        }

        public Criteria andOidPartnerBetween(String value1, String value2) {
            addCriterion("oid_partner between", value1, value2, "oidPartner");
            return (Criteria) this;
        }

        public Criteria andOidPartnerNotBetween(String value1, String value2) {
            addCriterion("oid_partner not between", value1, value2, "oidPartner");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameIsNull() {
            addCriterion("enterprise_name is null");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameIsNotNull() {
            addCriterion("enterprise_name is not null");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameEqualTo(String value) {
            addCriterion("enterprise_name =", value, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameNotEqualTo(String value) {
            addCriterion("enterprise_name <>", value, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameGreaterThan(String value) {
            addCriterion("enterprise_name >", value, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameGreaterThanOrEqualTo(String value) {
            addCriterion("enterprise_name >=", value, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameLessThan(String value) {
            addCriterion("enterprise_name <", value, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameLessThanOrEqualTo(String value) {
            addCriterion("enterprise_name <=", value, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameLike(String value) {
            addCriterion("enterprise_name like", value, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameNotLike(String value) {
            addCriterion("enterprise_name not like", value, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameIn(List<String> values) {
            addCriterion("enterprise_name in", values, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameNotIn(List<String> values) {
            addCriterion("enterprise_name not in", values, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameBetween(String value1, String value2) {
            addCriterion("enterprise_name between", value1, value2, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameNotBetween(String value1, String value2) {
            addCriterion("enterprise_name not between", value1, value2, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andCoEnterpriseIdIsNull() {
            addCriterion("co_enterprise_id is null");
            return (Criteria) this;
        }

        public Criteria andCoEnterpriseIdIsNotNull() {
            addCriterion("co_enterprise_id is not null");
            return (Criteria) this;
        }

        public Criteria andCoEnterpriseIdEqualTo(String value) {
            addCriterion("co_enterprise_id =", value, "coEnterpriseId");
            return (Criteria) this;
        }

        public Criteria andCoEnterpriseIdNotEqualTo(String value) {
            addCriterion("co_enterprise_id <>", value, "coEnterpriseId");
            return (Criteria) this;
        }

        public Criteria andCoEnterpriseIdGreaterThan(String value) {
            addCriterion("co_enterprise_id >", value, "coEnterpriseId");
            return (Criteria) this;
        }

        public Criteria andCoEnterpriseIdGreaterThanOrEqualTo(String value) {
            addCriterion("co_enterprise_id >=", value, "coEnterpriseId");
            return (Criteria) this;
        }

        public Criteria andCoEnterpriseIdLessThan(String value) {
            addCriterion("co_enterprise_id <", value, "coEnterpriseId");
            return (Criteria) this;
        }

        public Criteria andCoEnterpriseIdLessThanOrEqualTo(String value) {
            addCriterion("co_enterprise_id <=", value, "coEnterpriseId");
            return (Criteria) this;
        }

        public Criteria andCoEnterpriseIdLike(String value) {
            addCriterion("co_enterprise_id like", value, "coEnterpriseId");
            return (Criteria) this;
        }

        public Criteria andCoEnterpriseIdNotLike(String value) {
            addCriterion("co_enterprise_id not like", value, "coEnterpriseId");
            return (Criteria) this;
        }

        public Criteria andCoEnterpriseIdIn(List<String> values) {
            addCriterion("co_enterprise_id in", values, "coEnterpriseId");
            return (Criteria) this;
        }

        public Criteria andCoEnterpriseIdNotIn(List<String> values) {
            addCriterion("co_enterprise_id not in", values, "coEnterpriseId");
            return (Criteria) this;
        }

        public Criteria andCoEnterpriseIdBetween(String value1, String value2) {
            addCriterion("co_enterprise_id between", value1, value2, "coEnterpriseId");
            return (Criteria) this;
        }

        public Criteria andCoEnterpriseIdNotBetween(String value1, String value2) {
            addCriterion("co_enterprise_id not between", value1, value2, "coEnterpriseId");
            return (Criteria) this;
        }

        public Criteria andSummaryNameIsNull() {
            addCriterion("summary_name is null");
            return (Criteria) this;
        }

        public Criteria andSummaryNameIsNotNull() {
            addCriterion("summary_name is not null");
            return (Criteria) this;
        }

        public Criteria andSummaryNameEqualTo(String value) {
            addCriterion("summary_name =", value, "summaryName");
            return (Criteria) this;
        }

        public Criteria andSummaryNameNotEqualTo(String value) {
            addCriterion("summary_name <>", value, "summaryName");
            return (Criteria) this;
        }

        public Criteria andSummaryNameGreaterThan(String value) {
            addCriterion("summary_name >", value, "summaryName");
            return (Criteria) this;
        }

        public Criteria andSummaryNameGreaterThanOrEqualTo(String value) {
            addCriterion("summary_name >=", value, "summaryName");
            return (Criteria) this;
        }

        public Criteria andSummaryNameLessThan(String value) {
            addCriterion("summary_name <", value, "summaryName");
            return (Criteria) this;
        }

        public Criteria andSummaryNameLessThanOrEqualTo(String value) {
            addCriterion("summary_name <=", value, "summaryName");
            return (Criteria) this;
        }

        public Criteria andSummaryNameLike(String value) {
            addCriterion("summary_name like", value, "summaryName");
            return (Criteria) this;
        }

        public Criteria andSummaryNameNotLike(String value) {
            addCriterion("summary_name not like", value, "summaryName");
            return (Criteria) this;
        }

        public Criteria andSummaryNameIn(List<String> values) {
            addCriterion("summary_name in", values, "summaryName");
            return (Criteria) this;
        }

        public Criteria andSummaryNameNotIn(List<String> values) {
            addCriterion("summary_name not in", values, "summaryName");
            return (Criteria) this;
        }

        public Criteria andSummaryNameBetween(String value1, String value2) {
            addCriterion("summary_name between", value1, value2, "summaryName");
            return (Criteria) this;
        }

        public Criteria andSummaryNameNotBetween(String value1, String value2) {
            addCriterion("summary_name not between", value1, value2, "summaryName");
            return (Criteria) this;
        }

        public Criteria andGrantMonthIsNull() {
            addCriterion("grant_month is null");
            return (Criteria) this;
        }

        public Criteria andGrantMonthIsNotNull() {
            addCriterion("grant_month is not null");
            return (Criteria) this;
        }

        public Criteria andGrantMonthEqualTo(String value) {
            addCriterion("grant_month =", value, "grantMonth");
            return (Criteria) this;
        }

        public Criteria andGrantMonthNotEqualTo(String value) {
            addCriterion("grant_month <>", value, "grantMonth");
            return (Criteria) this;
        }

        public Criteria andGrantMonthGreaterThan(String value) {
            addCriterion("grant_month >", value, "grantMonth");
            return (Criteria) this;
        }

        public Criteria andGrantMonthGreaterThanOrEqualTo(String value) {
            addCriterion("grant_month >=", value, "grantMonth");
            return (Criteria) this;
        }

        public Criteria andGrantMonthLessThan(String value) {
            addCriterion("grant_month <", value, "grantMonth");
            return (Criteria) this;
        }

        public Criteria andGrantMonthLessThanOrEqualTo(String value) {
            addCriterion("grant_month <=", value, "grantMonth");
            return (Criteria) this;
        }

        public Criteria andGrantMonthLike(String value) {
            addCriterion("grant_month like", value, "grantMonth");
            return (Criteria) this;
        }

        public Criteria andGrantMonthNotLike(String value) {
            addCriterion("grant_month not like", value, "grantMonth");
            return (Criteria) this;
        }

        public Criteria andGrantMonthIn(List<String> values) {
            addCriterion("grant_month in", values, "grantMonth");
            return (Criteria) this;
        }

        public Criteria andGrantMonthNotIn(List<String> values) {
            addCriterion("grant_month not in", values, "grantMonth");
            return (Criteria) this;
        }

        public Criteria andGrantMonthBetween(String value1, String value2) {
            addCriterion("grant_month between", value1, value2, "grantMonth");
            return (Criteria) this;
        }

        public Criteria andGrantMonthNotBetween(String value1, String value2) {
            addCriterion("grant_month not between", value1, value2, "grantMonth");
            return (Criteria) this;
        }

        public Criteria andSummaryNumIsNull() {
            addCriterion("summary_num is null");
            return (Criteria) this;
        }

        public Criteria andSummaryNumIsNotNull() {
            addCriterion("summary_num is not null");
            return (Criteria) this;
        }

        public Criteria andSummaryNumEqualTo(Integer value) {
            addCriterion("summary_num =", value, "summaryNum");
            return (Criteria) this;
        }

        public Criteria andSummaryNumNotEqualTo(Integer value) {
            addCriterion("summary_num <>", value, "summaryNum");
            return (Criteria) this;
        }

        public Criteria andSummaryNumGreaterThan(Integer value) {
            addCriterion("summary_num >", value, "summaryNum");
            return (Criteria) this;
        }

        public Criteria andSummaryNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("summary_num >=", value, "summaryNum");
            return (Criteria) this;
        }

        public Criteria andSummaryNumLessThan(Integer value) {
            addCriterion("summary_num <", value, "summaryNum");
            return (Criteria) this;
        }

        public Criteria andSummaryNumLessThanOrEqualTo(Integer value) {
            addCriterion("summary_num <=", value, "summaryNum");
            return (Criteria) this;
        }

        public Criteria andSummaryNumIn(List<Integer> values) {
            addCriterion("summary_num in", values, "summaryNum");
            return (Criteria) this;
        }

        public Criteria andSummaryNumNotIn(List<Integer> values) {
            addCriterion("summary_num not in", values, "summaryNum");
            return (Criteria) this;
        }

        public Criteria andSummaryNumBetween(Integer value1, Integer value2) {
            addCriterion("summary_num between", value1, value2, "summaryNum");
            return (Criteria) this;
        }

        public Criteria andSummaryNumNotBetween(Integer value1, Integer value2) {
            addCriterion("summary_num not between", value1, value2, "summaryNum");
            return (Criteria) this;
        }

        public Criteria andSummaryAmountIsNull() {
            addCriterion("summary_amount is null");
            return (Criteria) this;
        }

        public Criteria andSummaryAmountIsNotNull() {
            addCriterion("summary_amount is not null");
            return (Criteria) this;
        }

        public Criteria andSummaryAmountEqualTo(Long value) {
            addCriterion("summary_amount =", value, "summaryAmount");
            return (Criteria) this;
        }

        public Criteria andSummaryAmountNotEqualTo(Long value) {
            addCriterion("summary_amount <>", value, "summaryAmount");
            return (Criteria) this;
        }

        public Criteria andSummaryAmountGreaterThan(Long value) {
            addCriterion("summary_amount >", value, "summaryAmount");
            return (Criteria) this;
        }

        public Criteria andSummaryAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("summary_amount >=", value, "summaryAmount");
            return (Criteria) this;
        }

        public Criteria andSummaryAmountLessThan(Long value) {
            addCriterion("summary_amount <", value, "summaryAmount");
            return (Criteria) this;
        }

        public Criteria andSummaryAmountLessThanOrEqualTo(Long value) {
            addCriterion("summary_amount <=", value, "summaryAmount");
            return (Criteria) this;
        }

        public Criteria andSummaryAmountIn(List<Long> values) {
            addCriterion("summary_amount in", values, "summaryAmount");
            return (Criteria) this;
        }

        public Criteria andSummaryAmountNotIn(List<Long> values) {
            addCriterion("summary_amount not in", values, "summaryAmount");
            return (Criteria) this;
        }

        public Criteria andSummaryAmountBetween(Long value1, Long value2) {
            addCriterion("summary_amount between", value1, value2, "summaryAmount");
            return (Criteria) this;
        }

        public Criteria andSummaryAmountNotBetween(Long value1, Long value2) {
            addCriterion("summary_amount not between", value1, value2, "summaryAmount");
            return (Criteria) this;
        }

        public Criteria andGrantStateIsNull() {
            addCriterion("grant_state is null");
            return (Criteria) this;
        }

        public Criteria andGrantStateIsNotNull() {
            addCriterion("grant_state is not null");
            return (Criteria) this;
        }

        public Criteria andGrantStateEqualTo(String value) {
            addCriterion("grant_state =", value, "grantState");
            return (Criteria) this;
        }

        public Criteria andGrantStateNotEqualTo(String value) {
            addCriterion("grant_state <>", value, "grantState");
            return (Criteria) this;
        }

        public Criteria andGrantStateGreaterThan(String value) {
            addCriterion("grant_state >", value, "grantState");
            return (Criteria) this;
        }

        public Criteria andGrantStateGreaterThanOrEqualTo(String value) {
            addCriterion("grant_state >=", value, "grantState");
            return (Criteria) this;
        }

        public Criteria andGrantStateLessThan(String value) {
            addCriterion("grant_state <", value, "grantState");
            return (Criteria) this;
        }

        public Criteria andGrantStateLessThanOrEqualTo(String value) {
            addCriterion("grant_state <=", value, "grantState");
            return (Criteria) this;
        }

        public Criteria andGrantStateLike(String value) {
            addCriterion("grant_state like", value, "grantState");
            return (Criteria) this;
        }

        public Criteria andGrantStateNotLike(String value) {
            addCriterion("grant_state not like", value, "grantState");
            return (Criteria) this;
        }

        public Criteria andGrantStateIn(List<String> values) {
            addCriterion("grant_state in", values, "grantState");
            return (Criteria) this;
        }

        public Criteria andGrantStateNotIn(List<String> values) {
            addCriterion("grant_state not in", values, "grantState");
            return (Criteria) this;
        }

        public Criteria andGrantStateBetween(String value1, String value2) {
            addCriterion("grant_state between", value1, value2, "grantState");
            return (Criteria) this;
        }

        public Criteria andGrantStateNotBetween(String value1, String value2) {
            addCriterion("grant_state not between", value1, value2, "grantState");
            return (Criteria) this;
        }

        public Criteria andAuditStateIsNull() {
            addCriterion("audit_state is null");
            return (Criteria) this;
        }

        public Criteria andAuditStateIsNotNull() {
            addCriterion("audit_state is not null");
            return (Criteria) this;
        }

        public Criteria andAuditStateEqualTo(String value) {
            addCriterion("audit_state =", value, "auditState");
            return (Criteria) this;
        }

        public Criteria andAuditStateNotEqualTo(String value) {
            addCriterion("audit_state <>", value, "auditState");
            return (Criteria) this;
        }

        public Criteria andAuditStateGreaterThan(String value) {
            addCriterion("audit_state >", value, "auditState");
            return (Criteria) this;
        }

        public Criteria andAuditStateGreaterThanOrEqualTo(String value) {
            addCriterion("audit_state >=", value, "auditState");
            return (Criteria) this;
        }

        public Criteria andAuditStateLessThan(String value) {
            addCriterion("audit_state <", value, "auditState");
            return (Criteria) this;
        }

        public Criteria andAuditStateLessThanOrEqualTo(String value) {
            addCriterion("audit_state <=", value, "auditState");
            return (Criteria) this;
        }

        public Criteria andAuditStateLike(String value) {
            addCriterion("audit_state like", value, "auditState");
            return (Criteria) this;
        }

        public Criteria andAuditStateNotLike(String value) {
            addCriterion("audit_state not like", value, "auditState");
            return (Criteria) this;
        }

        public Criteria andAuditStateIn(List<String> values) {
            addCriterion("audit_state in", values, "auditState");
            return (Criteria) this;
        }

        public Criteria andAuditStateNotIn(List<String> values) {
            addCriterion("audit_state not in", values, "auditState");
            return (Criteria) this;
        }

        public Criteria andAuditStateBetween(String value1, String value2) {
            addCriterion("audit_state between", value1, value2, "auditState");
            return (Criteria) this;
        }

        public Criteria andAuditStateNotBetween(String value1, String value2) {
            addCriterion("audit_state not between", value1, value2, "auditState");
            return (Criteria) this;
        }

        public Criteria andSuccessSumIsNull() {
            addCriterion("success_sum is null");
            return (Criteria) this;
        }

        public Criteria andSuccessSumIsNotNull() {
            addCriterion("success_sum is not null");
            return (Criteria) this;
        }

        public Criteria andSuccessSumEqualTo(Short value) {
            addCriterion("success_sum =", value, "successSum");
            return (Criteria) this;
        }

        public Criteria andSuccessSumNotEqualTo(Short value) {
            addCriterion("success_sum <>", value, "successSum");
            return (Criteria) this;
        }

        public Criteria andSuccessSumGreaterThan(Short value) {
            addCriterion("success_sum >", value, "successSum");
            return (Criteria) this;
        }

        public Criteria andSuccessSumGreaterThanOrEqualTo(Short value) {
            addCriterion("success_sum >=", value, "successSum");
            return (Criteria) this;
        }

        public Criteria andSuccessSumLessThan(Short value) {
            addCriterion("success_sum <", value, "successSum");
            return (Criteria) this;
        }

        public Criteria andSuccessSumLessThanOrEqualTo(Short value) {
            addCriterion("success_sum <=", value, "successSum");
            return (Criteria) this;
        }

        public Criteria andSuccessSumIn(List<Short> values) {
            addCriterion("success_sum in", values, "successSum");
            return (Criteria) this;
        }

        public Criteria andSuccessSumNotIn(List<Short> values) {
            addCriterion("success_sum not in", values, "successSum");
            return (Criteria) this;
        }

        public Criteria andSuccessSumBetween(Short value1, Short value2) {
            addCriterion("success_sum between", value1, value2, "successSum");
            return (Criteria) this;
        }

        public Criteria andSuccessSumNotBetween(Short value1, Short value2) {
            addCriterion("success_sum not between", value1, value2, "successSum");
            return (Criteria) this;
        }

        public Criteria andSuccessAmountIsNull() {
            addCriterion("success_amount is null");
            return (Criteria) this;
        }

        public Criteria andSuccessAmountIsNotNull() {
            addCriterion("success_amount is not null");
            return (Criteria) this;
        }

        public Criteria andSuccessAmountEqualTo(Long value) {
            addCriterion("success_amount =", value, "successAmount");
            return (Criteria) this;
        }

        public Criteria andSuccessAmountNotEqualTo(Long value) {
            addCriterion("success_amount <>", value, "successAmount");
            return (Criteria) this;
        }

        public Criteria andSuccessAmountGreaterThan(Long value) {
            addCriterion("success_amount >", value, "successAmount");
            return (Criteria) this;
        }

        public Criteria andSuccessAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("success_amount >=", value, "successAmount");
            return (Criteria) this;
        }

        public Criteria andSuccessAmountLessThan(Long value) {
            addCriterion("success_amount <", value, "successAmount");
            return (Criteria) this;
        }

        public Criteria andSuccessAmountLessThanOrEqualTo(Long value) {
            addCriterion("success_amount <=", value, "successAmount");
            return (Criteria) this;
        }

        public Criteria andSuccessAmountIn(List<Long> values) {
            addCriterion("success_amount in", values, "successAmount");
            return (Criteria) this;
        }

        public Criteria andSuccessAmountNotIn(List<Long> values) {
            addCriterion("success_amount not in", values, "successAmount");
            return (Criteria) this;
        }

        public Criteria andSuccessAmountBetween(Long value1, Long value2) {
            addCriterion("success_amount between", value1, value2, "successAmount");
            return (Criteria) this;
        }

        public Criteria andSuccessAmountNotBetween(Long value1, Long value2) {
            addCriterion("success_amount not between", value1, value2, "successAmount");
            return (Criteria) this;
        }

        public Criteria andFailSumIsNull() {
            addCriterion("fail_sum is null");
            return (Criteria) this;
        }

        public Criteria andFailSumIsNotNull() {
            addCriterion("fail_sum is not null");
            return (Criteria) this;
        }

        public Criteria andFailSumEqualTo(Short value) {
            addCriterion("fail_sum =", value, "failSum");
            return (Criteria) this;
        }

        public Criteria andFailSumNotEqualTo(Short value) {
            addCriterion("fail_sum <>", value, "failSum");
            return (Criteria) this;
        }

        public Criteria andFailSumGreaterThan(Short value) {
            addCriterion("fail_sum >", value, "failSum");
            return (Criteria) this;
        }

        public Criteria andFailSumGreaterThanOrEqualTo(Short value) {
            addCriterion("fail_sum >=", value, "failSum");
            return (Criteria) this;
        }

        public Criteria andFailSumLessThan(Short value) {
            addCriterion("fail_sum <", value, "failSum");
            return (Criteria) this;
        }

        public Criteria andFailSumLessThanOrEqualTo(Short value) {
            addCriterion("fail_sum <=", value, "failSum");
            return (Criteria) this;
        }

        public Criteria andFailSumIn(List<Short> values) {
            addCriterion("fail_sum in", values, "failSum");
            return (Criteria) this;
        }

        public Criteria andFailSumNotIn(List<Short> values) {
            addCriterion("fail_sum not in", values, "failSum");
            return (Criteria) this;
        }

        public Criteria andFailSumBetween(Short value1, Short value2) {
            addCriterion("fail_sum between", value1, value2, "failSum");
            return (Criteria) this;
        }

        public Criteria andFailSumNotBetween(Short value1, Short value2) {
            addCriterion("fail_sum not between", value1, value2, "failSum");
            return (Criteria) this;
        }

        public Criteria andFailAmountIsNull() {
            addCriterion("fail_amount is null");
            return (Criteria) this;
        }

        public Criteria andFailAmountIsNotNull() {
            addCriterion("fail_amount is not null");
            return (Criteria) this;
        }

        public Criteria andFailAmountEqualTo(Long value) {
            addCriterion("fail_amount =", value, "failAmount");
            return (Criteria) this;
        }

        public Criteria andFailAmountNotEqualTo(Long value) {
            addCriterion("fail_amount <>", value, "failAmount");
            return (Criteria) this;
        }

        public Criteria andFailAmountGreaterThan(Long value) {
            addCriterion("fail_amount >", value, "failAmount");
            return (Criteria) this;
        }

        public Criteria andFailAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("fail_amount >=", value, "failAmount");
            return (Criteria) this;
        }

        public Criteria andFailAmountLessThan(Long value) {
            addCriterion("fail_amount <", value, "failAmount");
            return (Criteria) this;
        }

        public Criteria andFailAmountLessThanOrEqualTo(Long value) {
            addCriterion("fail_amount <=", value, "failAmount");
            return (Criteria) this;
        }

        public Criteria andFailAmountIn(List<Long> values) {
            addCriterion("fail_amount in", values, "failAmount");
            return (Criteria) this;
        }

        public Criteria andFailAmountNotIn(List<Long> values) {
            addCriterion("fail_amount not in", values, "failAmount");
            return (Criteria) this;
        }

        public Criteria andFailAmountBetween(Long value1, Long value2) {
            addCriterion("fail_amount between", value1, value2, "failAmount");
            return (Criteria) this;
        }

        public Criteria andFailAmountNotBetween(Long value1, Long value2) {
            addCriterion("fail_amount not between", value1, value2, "failAmount");
            return (Criteria) this;
        }

        public Criteria andRemitSumIsNull() {
            addCriterion("remit_sum is null");
            return (Criteria) this;
        }

        public Criteria andRemitSumIsNotNull() {
            addCriterion("remit_sum is not null");
            return (Criteria) this;
        }

        public Criteria andRemitSumEqualTo(Short value) {
            addCriterion("remit_sum =", value, "remitSum");
            return (Criteria) this;
        }

        public Criteria andRemitSumNotEqualTo(Short value) {
            addCriterion("remit_sum <>", value, "remitSum");
            return (Criteria) this;
        }

        public Criteria andRemitSumGreaterThan(Short value) {
            addCriterion("remit_sum >", value, "remitSum");
            return (Criteria) this;
        }

        public Criteria andRemitSumGreaterThanOrEqualTo(Short value) {
            addCriterion("remit_sum >=", value, "remitSum");
            return (Criteria) this;
        }

        public Criteria andRemitSumLessThan(Short value) {
            addCriterion("remit_sum <", value, "remitSum");
            return (Criteria) this;
        }

        public Criteria andRemitSumLessThanOrEqualTo(Short value) {
            addCriterion("remit_sum <=", value, "remitSum");
            return (Criteria) this;
        }

        public Criteria andRemitSumIn(List<Short> values) {
            addCriterion("remit_sum in", values, "remitSum");
            return (Criteria) this;
        }

        public Criteria andRemitSumNotIn(List<Short> values) {
            addCriterion("remit_sum not in", values, "remitSum");
            return (Criteria) this;
        }

        public Criteria andRemitSumBetween(Short value1, Short value2) {
            addCriterion("remit_sum between", value1, value2, "remitSum");
            return (Criteria) this;
        }

        public Criteria andRemitSumNotBetween(Short value1, Short value2) {
            addCriterion("remit_sum not between", value1, value2, "remitSum");
            return (Criteria) this;
        }

        public Criteria andRemitAmountIsNull() {
            addCriterion("remit_amount is null");
            return (Criteria) this;
        }

        public Criteria andRemitAmountIsNotNull() {
            addCriterion("remit_amount is not null");
            return (Criteria) this;
        }

        public Criteria andRemitAmountEqualTo(Long value) {
            addCriterion("remit_amount =", value, "remitAmount");
            return (Criteria) this;
        }

        public Criteria andRemitAmountNotEqualTo(Long value) {
            addCriterion("remit_amount <>", value, "remitAmount");
            return (Criteria) this;
        }

        public Criteria andRemitAmountGreaterThan(Long value) {
            addCriterion("remit_amount >", value, "remitAmount");
            return (Criteria) this;
        }

        public Criteria andRemitAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("remit_amount >=", value, "remitAmount");
            return (Criteria) this;
        }

        public Criteria andRemitAmountLessThan(Long value) {
            addCriterion("remit_amount <", value, "remitAmount");
            return (Criteria) this;
        }

        public Criteria andRemitAmountLessThanOrEqualTo(Long value) {
            addCriterion("remit_amount <=", value, "remitAmount");
            return (Criteria) this;
        }

        public Criteria andRemitAmountIn(List<Long> values) {
            addCriterion("remit_amount in", values, "remitAmount");
            return (Criteria) this;
        }

        public Criteria andRemitAmountNotIn(List<Long> values) {
            addCriterion("remit_amount not in", values, "remitAmount");
            return (Criteria) this;
        }

        public Criteria andRemitAmountBetween(Long value1, Long value2) {
            addCriterion("remit_amount between", value1, value2, "remitAmount");
            return (Criteria) this;
        }

        public Criteria andRemitAmountNotBetween(Long value1, Long value2) {
            addCriterion("remit_amount not between", value1, value2, "remitAmount");
            return (Criteria) this;
        }

        public Criteria andFormCreaterIsNull() {
            addCriterion("form_creater is null");
            return (Criteria) this;
        }

        public Criteria andFormCreaterIsNotNull() {
            addCriterion("form_creater is not null");
            return (Criteria) this;
        }

        public Criteria andFormCreaterEqualTo(String value) {
            addCriterion("form_creater =", value, "formCreater");
            return (Criteria) this;
        }

        public Criteria andFormCreaterNotEqualTo(String value) {
            addCriterion("form_creater <>", value, "formCreater");
            return (Criteria) this;
        }

        public Criteria andFormCreaterGreaterThan(String value) {
            addCriterion("form_creater >", value, "formCreater");
            return (Criteria) this;
        }

        public Criteria andFormCreaterGreaterThanOrEqualTo(String value) {
            addCriterion("form_creater >=", value, "formCreater");
            return (Criteria) this;
        }

        public Criteria andFormCreaterLessThan(String value) {
            addCriterion("form_creater <", value, "formCreater");
            return (Criteria) this;
        }

        public Criteria andFormCreaterLessThanOrEqualTo(String value) {
            addCriterion("form_creater <=", value, "formCreater");
            return (Criteria) this;
        }

        public Criteria andFormCreaterLike(String value) {
            addCriterion("form_creater like", value, "formCreater");
            return (Criteria) this;
        }

        public Criteria andFormCreaterNotLike(String value) {
            addCriterion("form_creater not like", value, "formCreater");
            return (Criteria) this;
        }

        public Criteria andFormCreaterIn(List<String> values) {
            addCriterion("form_creater in", values, "formCreater");
            return (Criteria) this;
        }

        public Criteria andFormCreaterNotIn(List<String> values) {
            addCriterion("form_creater not in", values, "formCreater");
            return (Criteria) this;
        }

        public Criteria andFormCreaterBetween(String value1, String value2) {
            addCriterion("form_creater between", value1, value2, "formCreater");
            return (Criteria) this;
        }

        public Criteria andFormCreaterNotBetween(String value1, String value2) {
            addCriterion("form_creater not between", value1, value2, "formCreater");
            return (Criteria) this;
        }

        public Criteria andGrantAuditorIsNull() {
            addCriterion("grant_auditor is null");
            return (Criteria) this;
        }

        public Criteria andGrantAuditorIsNotNull() {
            addCriterion("grant_auditor is not null");
            return (Criteria) this;
        }

        public Criteria andGrantAuditorEqualTo(String value) {
            addCriterion("grant_auditor =", value, "grantAuditor");
            return (Criteria) this;
        }

        public Criteria andGrantAuditorNotEqualTo(String value) {
            addCriterion("grant_auditor <>", value, "grantAuditor");
            return (Criteria) this;
        }

        public Criteria andGrantAuditorGreaterThan(String value) {
            addCriterion("grant_auditor >", value, "grantAuditor");
            return (Criteria) this;
        }

        public Criteria andGrantAuditorGreaterThanOrEqualTo(String value) {
            addCriterion("grant_auditor >=", value, "grantAuditor");
            return (Criteria) this;
        }

        public Criteria andGrantAuditorLessThan(String value) {
            addCriterion("grant_auditor <", value, "grantAuditor");
            return (Criteria) this;
        }

        public Criteria andGrantAuditorLessThanOrEqualTo(String value) {
            addCriterion("grant_auditor <=", value, "grantAuditor");
            return (Criteria) this;
        }

        public Criteria andGrantAuditorLike(String value) {
            addCriterion("grant_auditor like", value, "grantAuditor");
            return (Criteria) this;
        }

        public Criteria andGrantAuditorNotLike(String value) {
            addCriterion("grant_auditor not like", value, "grantAuditor");
            return (Criteria) this;
        }

        public Criteria andGrantAuditorIn(List<String> values) {
            addCriterion("grant_auditor in", values, "grantAuditor");
            return (Criteria) this;
        }

        public Criteria andGrantAuditorNotIn(List<String> values) {
            addCriterion("grant_auditor not in", values, "grantAuditor");
            return (Criteria) this;
        }

        public Criteria andGrantAuditorBetween(String value1, String value2) {
            addCriterion("grant_auditor between", value1, value2, "grantAuditor");
            return (Criteria) this;
        }

        public Criteria andGrantAuditorNotBetween(String value1, String value2) {
            addCriterion("grant_auditor not between", value1, value2, "grantAuditor");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andSalaryBillTitleIsNull() {
            addCriterion("salary_bill_title is null");
            return (Criteria) this;
        }

        public Criteria andSalaryBillTitleIsNotNull() {
            addCriterion("salary_bill_title is not null");
            return (Criteria) this;
        }

        public Criteria andSalaryBillTitleEqualTo(String value) {
            addCriterion("salary_bill_title =", value, "salaryBillTitle");
            return (Criteria) this;
        }

        public Criteria andSalaryBillTitleNotEqualTo(String value) {
            addCriterion("salary_bill_title <>", value, "salaryBillTitle");
            return (Criteria) this;
        }

        public Criteria andSalaryBillTitleGreaterThan(String value) {
            addCriterion("salary_bill_title >", value, "salaryBillTitle");
            return (Criteria) this;
        }

        public Criteria andSalaryBillTitleGreaterThanOrEqualTo(String value) {
            addCriterion("salary_bill_title >=", value, "salaryBillTitle");
            return (Criteria) this;
        }

        public Criteria andSalaryBillTitleLessThan(String value) {
            addCriterion("salary_bill_title <", value, "salaryBillTitle");
            return (Criteria) this;
        }

        public Criteria andSalaryBillTitleLessThanOrEqualTo(String value) {
            addCriterion("salary_bill_title <=", value, "salaryBillTitle");
            return (Criteria) this;
        }

        public Criteria andSalaryBillTitleLike(String value) {
            addCriterion("salary_bill_title like", value, "salaryBillTitle");
            return (Criteria) this;
        }

        public Criteria andSalaryBillTitleNotLike(String value) {
            addCriterion("salary_bill_title not like", value, "salaryBillTitle");
            return (Criteria) this;
        }

        public Criteria andSalaryBillTitleIn(List<String> values) {
            addCriterion("salary_bill_title in", values, "salaryBillTitle");
            return (Criteria) this;
        }

        public Criteria andSalaryBillTitleNotIn(List<String> values) {
            addCriterion("salary_bill_title not in", values, "salaryBillTitle");
            return (Criteria) this;
        }

        public Criteria andSalaryBillTitleBetween(String value1, String value2) {
            addCriterion("salary_bill_title between", value1, value2, "salaryBillTitle");
            return (Criteria) this;
        }

        public Criteria andSalaryBillTitleNotBetween(String value1, String value2) {
            addCriterion("salary_bill_title not between", value1, value2, "salaryBillTitle");
            return (Criteria) this;
        }

        public Criteria andBillSendFlagIsNull() {
            addCriterion("bill_send_flag is null");
            return (Criteria) this;
        }

        public Criteria andBillSendFlagIsNotNull() {
            addCriterion("bill_send_flag is not null");
            return (Criteria) this;
        }

        public Criteria andBillSendFlagEqualTo(String value) {
            addCriterion("bill_send_flag =", value, "billSendFlag");
            return (Criteria) this;
        }

        public Criteria andBillSendFlagNotEqualTo(String value) {
            addCriterion("bill_send_flag <>", value, "billSendFlag");
            return (Criteria) this;
        }

        public Criteria andBillSendFlagGreaterThan(String value) {
            addCriterion("bill_send_flag >", value, "billSendFlag");
            return (Criteria) this;
        }

        public Criteria andBillSendFlagGreaterThanOrEqualTo(String value) {
            addCriterion("bill_send_flag >=", value, "billSendFlag");
            return (Criteria) this;
        }

        public Criteria andBillSendFlagLessThan(String value) {
            addCriterion("bill_send_flag <", value, "billSendFlag");
            return (Criteria) this;
        }

        public Criteria andBillSendFlagLessThanOrEqualTo(String value) {
            addCriterion("bill_send_flag <=", value, "billSendFlag");
            return (Criteria) this;
        }

        public Criteria andBillSendFlagLike(String value) {
            addCriterion("bill_send_flag like", value, "billSendFlag");
            return (Criteria) this;
        }

        public Criteria andBillSendFlagNotLike(String value) {
            addCriterion("bill_send_flag not like", value, "billSendFlag");
            return (Criteria) this;
        }

        public Criteria andBillSendFlagIn(List<String> values) {
            addCriterion("bill_send_flag in", values, "billSendFlag");
            return (Criteria) this;
        }

        public Criteria andBillSendFlagNotIn(List<String> values) {
            addCriterion("bill_send_flag not in", values, "billSendFlag");
            return (Criteria) this;
        }

        public Criteria andBillSendFlagBetween(String value1, String value2) {
            addCriterion("bill_send_flag between", value1, value2, "billSendFlag");
            return (Criteria) this;
        }

        public Criteria andBillSendFlagNotBetween(String value1, String value2) {
            addCriterion("bill_send_flag not between", value1, value2, "billSendFlag");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andStr1IsNull() {
            addCriterion("str1 is null");
            return (Criteria) this;
        }

        public Criteria andStr1IsNotNull() {
            addCriterion("str1 is not null");
            return (Criteria) this;
        }

        public Criteria andStr1EqualTo(String value) {
            addCriterion("str1 =", value, "str1");
            return (Criteria) this;
        }

        public Criteria andStr1NotEqualTo(String value) {
            addCriterion("str1 <>", value, "str1");
            return (Criteria) this;
        }

        public Criteria andStr1GreaterThan(String value) {
            addCriterion("str1 >", value, "str1");
            return (Criteria) this;
        }

        public Criteria andStr1GreaterThanOrEqualTo(String value) {
            addCriterion("str1 >=", value, "str1");
            return (Criteria) this;
        }

        public Criteria andStr1LessThan(String value) {
            addCriterion("str1 <", value, "str1");
            return (Criteria) this;
        }

        public Criteria andStr1LessThanOrEqualTo(String value) {
            addCriterion("str1 <=", value, "str1");
            return (Criteria) this;
        }

        public Criteria andStr1Like(String value) {
            addCriterion("str1 like", value, "str1");
            return (Criteria) this;
        }

        public Criteria andStr1NotLike(String value) {
            addCriterion("str1 not like", value, "str1");
            return (Criteria) this;
        }

        public Criteria andStr1In(List<String> values) {
            addCriterion("str1 in", values, "str1");
            return (Criteria) this;
        }

        public Criteria andStr1NotIn(List<String> values) {
            addCriterion("str1 not in", values, "str1");
            return (Criteria) this;
        }

        public Criteria andStr1Between(String value1, String value2) {
            addCriterion("str1 between", value1, value2, "str1");
            return (Criteria) this;
        }

        public Criteria andStr1NotBetween(String value1, String value2) {
            addCriterion("str1 not between", value1, value2, "str1");
            return (Criteria) this;
        }

        public Criteria andSummaryFilePathIsNull() {
            addCriterion("summary_file_path is null");
            return (Criteria) this;
        }

        public Criteria andSummaryFilePathIsNotNull() {
            addCriterion("summary_file_path is not null");
            return (Criteria) this;
        }

        public Criteria andSummaryFilePathEqualTo(String value) {
            addCriterion("summary_file_path =", value, "summaryFilePath");
            return (Criteria) this;
        }

        public Criteria andSummaryFilePathNotEqualTo(String value) {
            addCriterion("summary_file_path <>", value, "summaryFilePath");
            return (Criteria) this;
        }

        public Criteria andSummaryFilePathGreaterThan(String value) {
            addCriterion("summary_file_path >", value, "summaryFilePath");
            return (Criteria) this;
        }

        public Criteria andSummaryFilePathGreaterThanOrEqualTo(String value) {
            addCriterion("summary_file_path >=", value, "summaryFilePath");
            return (Criteria) this;
        }

        public Criteria andSummaryFilePathLessThan(String value) {
            addCriterion("summary_file_path <", value, "summaryFilePath");
            return (Criteria) this;
        }

        public Criteria andSummaryFilePathLessThanOrEqualTo(String value) {
            addCriterion("summary_file_path <=", value, "summaryFilePath");
            return (Criteria) this;
        }

        public Criteria andSummaryFilePathLike(String value) {
            addCriterion("summary_file_path like", value, "summaryFilePath");
            return (Criteria) this;
        }

        public Criteria andSummaryFilePathNotLike(String value) {
            addCriterion("summary_file_path not like", value, "summaryFilePath");
            return (Criteria) this;
        }

        public Criteria andSummaryFilePathIn(List<String> values) {
            addCriterion("summary_file_path in", values, "summaryFilePath");
            return (Criteria) this;
        }

        public Criteria andSummaryFilePathNotIn(List<String> values) {
            addCriterion("summary_file_path not in", values, "summaryFilePath");
            return (Criteria) this;
        }

        public Criteria andSummaryFilePathBetween(String value1, String value2) {
            addCriterion("summary_file_path between", value1, value2, "summaryFilePath");
            return (Criteria) this;
        }

        public Criteria andSummaryFilePathNotBetween(String value1, String value2) {
            addCriterion("summary_file_path not between", value1, value2, "summaryFilePath");
            return (Criteria) this;
        }

        public Criteria andPurposeIsNull() {
            addCriterion("purpose is null");
            return (Criteria) this;
        }

        public Criteria andPurposeIsNotNull() {
            addCriterion("purpose is not null");
            return (Criteria) this;
        }

        public Criteria andPurposeEqualTo(String value) {
            addCriterion("purpose =", value, "purpose");
            return (Criteria) this;
        }

        public Criteria andPurposeNotEqualTo(String value) {
            addCriterion("purpose <>", value, "purpose");
            return (Criteria) this;
        }

        public Criteria andPurposeGreaterThan(String value) {
            addCriterion("purpose >", value, "purpose");
            return (Criteria) this;
        }

        public Criteria andPurposeGreaterThanOrEqualTo(String value) {
            addCriterion("purpose >=", value, "purpose");
            return (Criteria) this;
        }

        public Criteria andPurposeLessThan(String value) {
            addCriterion("purpose <", value, "purpose");
            return (Criteria) this;
        }

        public Criteria andPurposeLessThanOrEqualTo(String value) {
            addCriterion("purpose <=", value, "purpose");
            return (Criteria) this;
        }

        public Criteria andPurposeLike(String value) {
            addCriterion("purpose like", value, "purpose");
            return (Criteria) this;
        }

        public Criteria andPurposeNotLike(String value) {
            addCriterion("purpose not like", value, "purpose");
            return (Criteria) this;
        }

        public Criteria andPurposeIn(List<String> values) {
            addCriterion("purpose in", values, "purpose");
            return (Criteria) this;
        }

        public Criteria andPurposeNotIn(List<String> values) {
            addCriterion("purpose not in", values, "purpose");
            return (Criteria) this;
        }

        public Criteria andPurposeBetween(String value1, String value2) {
            addCriterion("purpose between", value1, value2, "purpose");
            return (Criteria) this;
        }

        public Criteria andPurposeNotBetween(String value1, String value2) {
            addCriterion("purpose not between", value1, value2, "purpose");
            return (Criteria) this;
        }

        public Criteria andSummaryFileMd5IsNull() {
            addCriterion("summary_file_md5 is null");
            return (Criteria) this;
        }

        public Criteria andSummaryFileMd5IsNotNull() {
            addCriterion("summary_file_md5 is not null");
            return (Criteria) this;
        }

        public Criteria andSummaryFileMd5EqualTo(String value) {
            addCriterion("summary_file_md5 =", value, "summaryFileMd5");
            return (Criteria) this;
        }

        public Criteria andSummaryFileMd5NotEqualTo(String value) {
            addCriterion("summary_file_md5 <>", value, "summaryFileMd5");
            return (Criteria) this;
        }

        public Criteria andSummaryFileMd5GreaterThan(String value) {
            addCriterion("summary_file_md5 >", value, "summaryFileMd5");
            return (Criteria) this;
        }

        public Criteria andSummaryFileMd5GreaterThanOrEqualTo(String value) {
            addCriterion("summary_file_md5 >=", value, "summaryFileMd5");
            return (Criteria) this;
        }

        public Criteria andSummaryFileMd5LessThan(String value) {
            addCriterion("summary_file_md5 <", value, "summaryFileMd5");
            return (Criteria) this;
        }

        public Criteria andSummaryFileMd5LessThanOrEqualTo(String value) {
            addCriterion("summary_file_md5 <=", value, "summaryFileMd5");
            return (Criteria) this;
        }

        public Criteria andSummaryFileMd5Like(String value) {
            addCriterion("summary_file_md5 like", value, "summaryFileMd5");
            return (Criteria) this;
        }

        public Criteria andSummaryFileMd5NotLike(String value) {
            addCriterion("summary_file_md5 not like", value, "summaryFileMd5");
            return (Criteria) this;
        }

        public Criteria andSummaryFileMd5In(List<String> values) {
            addCriterion("summary_file_md5 in", values, "summaryFileMd5");
            return (Criteria) this;
        }

        public Criteria andSummaryFileMd5NotIn(List<String> values) {
            addCriterion("summary_file_md5 not in", values, "summaryFileMd5");
            return (Criteria) this;
        }

        public Criteria andSummaryFileMd5Between(String value1, String value2) {
            addCriterion("summary_file_md5 between", value1, value2, "summaryFileMd5");
            return (Criteria) this;
        }

        public Criteria andSummaryFileMd5NotBetween(String value1, String value2) {
            addCriterion("summary_file_md5 not between", value1, value2, "summaryFileMd5");
            return (Criteria) this;
        }

        public Criteria andRejectReasonIsNull() {
            addCriterion("reject_reason is null");
            return (Criteria) this;
        }

        public Criteria andRejectReasonIsNotNull() {
            addCriterion("reject_reason is not null");
            return (Criteria) this;
        }

        public Criteria andRejectReasonEqualTo(String value) {
            addCriterion("reject_reason =", value, "rejectReason");
            return (Criteria) this;
        }

        public Criteria andRejectReasonNotEqualTo(String value) {
            addCriterion("reject_reason <>", value, "rejectReason");
            return (Criteria) this;
        }

        public Criteria andRejectReasonGreaterThan(String value) {
            addCriterion("reject_reason >", value, "rejectReason");
            return (Criteria) this;
        }

        public Criteria andRejectReasonGreaterThanOrEqualTo(String value) {
            addCriterion("reject_reason >=", value, "rejectReason");
            return (Criteria) this;
        }

        public Criteria andRejectReasonLessThan(String value) {
            addCriterion("reject_reason <", value, "rejectReason");
            return (Criteria) this;
        }

        public Criteria andRejectReasonLessThanOrEqualTo(String value) {
            addCriterion("reject_reason <=", value, "rejectReason");
            return (Criteria) this;
        }

        public Criteria andRejectReasonLike(String value) {
            addCriterion("reject_reason like", value, "rejectReason");
            return (Criteria) this;
        }

        public Criteria andRejectReasonNotLike(String value) {
            addCriterion("reject_reason not like", value, "rejectReason");
            return (Criteria) this;
        }

        public Criteria andRejectReasonIn(List<String> values) {
            addCriterion("reject_reason in", values, "rejectReason");
            return (Criteria) this;
        }

        public Criteria andRejectReasonNotIn(List<String> values) {
            addCriterion("reject_reason not in", values, "rejectReason");
            return (Criteria) this;
        }

        public Criteria andRejectReasonBetween(String value1, String value2) {
            addCriterion("reject_reason between", value1, value2, "rejectReason");
            return (Criteria) this;
        }

        public Criteria andRejectReasonNotBetween(String value1, String value2) {
            addCriterion("reject_reason not between", value1, value2, "rejectReason");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_SALARY_SUMMARY
     *
     * @mbg.generated do_not_delete_during_merge Tue Jan 22 11:47:27 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_SALARY_SUMMARY
     *
     * @mbg.generated Tue Jan 22 11:47:27 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}