package com.chris.demo.core.auto;

import java.util.ArrayList;
import java.util.List;

public class Xf04RecordDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_xf04_record
     *
     * @mbg.generated Fri Sep 07 12:04:14 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_xf04_record
     *
     * @mbg.generated Fri Sep 07 12:04:14 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_xf04_record
     *
     * @mbg.generated Fri Sep 07 12:04:14 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_xf04_record
     *
     * @mbg.generated Fri Sep 07 12:04:14 CST 2018
     */
    public Xf04RecordDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_xf04_record
     *
     * @mbg.generated Fri Sep 07 12:04:14 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_xf04_record
     *
     * @mbg.generated Fri Sep 07 12:04:14 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_xf04_record
     *
     * @mbg.generated Fri Sep 07 12:04:14 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_xf04_record
     *
     * @mbg.generated Fri Sep 07 12:04:14 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_xf04_record
     *
     * @mbg.generated Fri Sep 07 12:04:14 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_xf04_record
     *
     * @mbg.generated Fri Sep 07 12:04:14 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_xf04_record
     *
     * @mbg.generated Fri Sep 07 12:04:14 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_xf04_record
     *
     * @mbg.generated Fri Sep 07 12:04:14 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_xf04_record
     *
     * @mbg.generated Fri Sep 07 12:04:14 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_xf04_record
     *
     * @mbg.generated Fri Sep 07 12:04:14 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_xf04_record
     *
     * @mbg.generated Fri Sep 07 12:04:14 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSerialnoIsNull() {
            addCriterion("serialno is null");
            return (Criteria) this;
        }

        public Criteria andSerialnoIsNotNull() {
            addCriterion("serialno is not null");
            return (Criteria) this;
        }

        public Criteria andSerialnoEqualTo(String value) {
            addCriterion("serialno =", value, "serialno");
            return (Criteria) this;
        }

        public Criteria andSerialnoNotEqualTo(String value) {
            addCriterion("serialno <>", value, "serialno");
            return (Criteria) this;
        }

        public Criteria andSerialnoGreaterThan(String value) {
            addCriterion("serialno >", value, "serialno");
            return (Criteria) this;
        }

        public Criteria andSerialnoGreaterThanOrEqualTo(String value) {
            addCriterion("serialno >=", value, "serialno");
            return (Criteria) this;
        }

        public Criteria andSerialnoLessThan(String value) {
            addCriterion("serialno <", value, "serialno");
            return (Criteria) this;
        }

        public Criteria andSerialnoLessThanOrEqualTo(String value) {
            addCriterion("serialno <=", value, "serialno");
            return (Criteria) this;
        }

        public Criteria andSerialnoLike(String value) {
            addCriterion("serialno like", value, "serialno");
            return (Criteria) this;
        }

        public Criteria andSerialnoNotLike(String value) {
            addCriterion("serialno not like", value, "serialno");
            return (Criteria) this;
        }

        public Criteria andSerialnoIn(List<String> values) {
            addCriterion("serialno in", values, "serialno");
            return (Criteria) this;
        }

        public Criteria andSerialnoNotIn(List<String> values) {
            addCriterion("serialno not in", values, "serialno");
            return (Criteria) this;
        }

        public Criteria andSerialnoBetween(String value1, String value2) {
            addCriterion("serialno between", value1, value2, "serialno");
            return (Criteria) this;
        }

        public Criteria andSerialnoNotBetween(String value1, String value2) {
            addCriterion("serialno not between", value1, value2, "serialno");
            return (Criteria) this;
        }

        public Criteria andBankSerNoIsNull() {
            addCriterion("bank_ser_no is null");
            return (Criteria) this;
        }

        public Criteria andBankSerNoIsNotNull() {
            addCriterion("bank_ser_no is not null");
            return (Criteria) this;
        }

        public Criteria andBankSerNoEqualTo(String value) {
            addCriterion("bank_ser_no =", value, "bankSerNo");
            return (Criteria) this;
        }

        public Criteria andBankSerNoNotEqualTo(String value) {
            addCriterion("bank_ser_no <>", value, "bankSerNo");
            return (Criteria) this;
        }

        public Criteria andBankSerNoGreaterThan(String value) {
            addCriterion("bank_ser_no >", value, "bankSerNo");
            return (Criteria) this;
        }

        public Criteria andBankSerNoGreaterThanOrEqualTo(String value) {
            addCriterion("bank_ser_no >=", value, "bankSerNo");
            return (Criteria) this;
        }

        public Criteria andBankSerNoLessThan(String value) {
            addCriterion("bank_ser_no <", value, "bankSerNo");
            return (Criteria) this;
        }

        public Criteria andBankSerNoLessThanOrEqualTo(String value) {
            addCriterion("bank_ser_no <=", value, "bankSerNo");
            return (Criteria) this;
        }

        public Criteria andBankSerNoLike(String value) {
            addCriterion("bank_ser_no like", value, "bankSerNo");
            return (Criteria) this;
        }

        public Criteria andBankSerNoNotLike(String value) {
            addCriterion("bank_ser_no not like", value, "bankSerNo");
            return (Criteria) this;
        }

        public Criteria andBankSerNoIn(List<String> values) {
            addCriterion("bank_ser_no in", values, "bankSerNo");
            return (Criteria) this;
        }

        public Criteria andBankSerNoNotIn(List<String> values) {
            addCriterion("bank_ser_no not in", values, "bankSerNo");
            return (Criteria) this;
        }

        public Criteria andBankSerNoBetween(String value1, String value2) {
            addCriterion("bank_ser_no between", value1, value2, "bankSerNo");
            return (Criteria) this;
        }

        public Criteria andBankSerNoNotBetween(String value1, String value2) {
            addCriterion("bank_ser_no not between", value1, value2, "bankSerNo");
            return (Criteria) this;
        }

        public Criteria andDateacctIsNull() {
            addCriterion("dateacct is null");
            return (Criteria) this;
        }

        public Criteria andDateacctIsNotNull() {
            addCriterion("dateacct is not null");
            return (Criteria) this;
        }

        public Criteria andDateacctEqualTo(String value) {
            addCriterion("dateacct =", value, "dateacct");
            return (Criteria) this;
        }

        public Criteria andDateacctNotEqualTo(String value) {
            addCriterion("dateacct <>", value, "dateacct");
            return (Criteria) this;
        }

        public Criteria andDateacctGreaterThan(String value) {
            addCriterion("dateacct >", value, "dateacct");
            return (Criteria) this;
        }

        public Criteria andDateacctGreaterThanOrEqualTo(String value) {
            addCriterion("dateacct >=", value, "dateacct");
            return (Criteria) this;
        }

        public Criteria andDateacctLessThan(String value) {
            addCriterion("dateacct <", value, "dateacct");
            return (Criteria) this;
        }

        public Criteria andDateacctLessThanOrEqualTo(String value) {
            addCriterion("dateacct <=", value, "dateacct");
            return (Criteria) this;
        }

        public Criteria andDateacctLike(String value) {
            addCriterion("dateacct like", value, "dateacct");
            return (Criteria) this;
        }

        public Criteria andDateacctNotLike(String value) {
            addCriterion("dateacct not like", value, "dateacct");
            return (Criteria) this;
        }

        public Criteria andDateacctIn(List<String> values) {
            addCriterion("dateacct in", values, "dateacct");
            return (Criteria) this;
        }

        public Criteria andDateacctNotIn(List<String> values) {
            addCriterion("dateacct not in", values, "dateacct");
            return (Criteria) this;
        }

        public Criteria andDateacctBetween(String value1, String value2) {
            addCriterion("dateacct between", value1, value2, "dateacct");
            return (Criteria) this;
        }

        public Criteria andDateacctNotBetween(String value1, String value2) {
            addCriterion("dateacct not between", value1, value2, "dateacct");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_xf04_record
     *
     * @mbg.generated do_not_delete_during_merge Fri Sep 07 12:04:14 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_xf04_record
     *
     * @mbg.generated Fri Sep 07 12:04:14 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}