package com.chris.demo.core.auto;

public class Xf04RecordDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_xf04_record.serialno
     *
     * @mbg.generated Fri Sep 07 12:04:14 CST 2018
     */
    private String serialno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_xf04_record.bank_ser_no
     *
     * @mbg.generated Fri Sep 07 12:04:14 CST 2018
     */
    private String bankSerNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_xf04_record.dateacct
     *
     * @mbg.generated Fri Sep 07 12:04:14 CST 2018
     */
    private String dateacct;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_xf04_record.serialno
     *
     * @return the value of tb_xf04_record.serialno
     *
     * @mbg.generated Fri Sep 07 12:04:14 CST 2018
     */
    public String getSerialno() {
        return serialno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_xf04_record.serialno
     *
     * @param serialno the value for tb_xf04_record.serialno
     *
     * @mbg.generated Fri Sep 07 12:04:14 CST 2018
     */
    public void setSerialno(String serialno) {
        this.serialno = serialno == null ? null : serialno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_xf04_record.bank_ser_no
     *
     * @return the value of tb_xf04_record.bank_ser_no
     *
     * @mbg.generated Fri Sep 07 12:04:14 CST 2018
     */
    public String getBankSerNo() {
        return bankSerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_xf04_record.bank_ser_no
     *
     * @param bankSerNo the value for tb_xf04_record.bank_ser_no
     *
     * @mbg.generated Fri Sep 07 12:04:14 CST 2018
     */
    public void setBankSerNo(String bankSerNo) {
        this.bankSerNo = bankSerNo == null ? null : bankSerNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_xf04_record.dateacct
     *
     * @return the value of tb_xf04_record.dateacct
     *
     * @mbg.generated Fri Sep 07 12:04:14 CST 2018
     */
    public String getDateacct() {
        return dateacct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_xf04_record.dateacct
     *
     * @param dateacct the value for tb_xf04_record.dateacct
     *
     * @mbg.generated Fri Sep 07 12:04:14 CST 2018
     */
    public void setDateacct(String dateacct) {
        this.dateacct = dateacct == null ? null : dateacct.trim();
    }
}