package com.chris.demo.core.auto.mapper;

import com.chris.demo.core.auto.ChnlPayProduct;
import com.chris.demo.core.auto.ChnlPayProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChnlPayProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHNL_PAY_PRODUCT
     *
     * @mbg.generated Tue Jul 10 09:52:39 CST 2018
     */
    long countByExample(ChnlPayProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHNL_PAY_PRODUCT
     *
     * @mbg.generated Tue Jul 10 09:52:39 CST 2018
     */
    int deleteByPrimaryKey(String prodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHNL_PAY_PRODUCT
     *
     * @mbg.generated Tue Jul 10 09:52:39 CST 2018
     */
    int insert(ChnlPayProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHNL_PAY_PRODUCT
     *
     * @mbg.generated Tue Jul 10 09:52:39 CST 2018
     */
    int insertSelective(ChnlPayProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHNL_PAY_PRODUCT
     *
     * @mbg.generated Tue Jul 10 09:52:39 CST 2018
     */
    List<ChnlPayProduct> selectByExample(ChnlPayProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHNL_PAY_PRODUCT
     *
     * @mbg.generated Tue Jul 10 09:52:39 CST 2018
     */
    ChnlPayProduct selectByPrimaryKey(String prodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHNL_PAY_PRODUCT
     *
     * @mbg.generated Tue Jul 10 09:52:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") ChnlPayProduct record, @Param("example") ChnlPayProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHNL_PAY_PRODUCT
     *
     * @mbg.generated Tue Jul 10 09:52:39 CST 2018
     */
    int updateByExample(@Param("record") ChnlPayProduct record, @Param("example") ChnlPayProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHNL_PAY_PRODUCT
     *
     * @mbg.generated Tue Jul 10 09:52:39 CST 2018
     */
    int updateByPrimaryKeySelective(ChnlPayProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHNL_PAY_PRODUCT
     *
     * @mbg.generated Tue Jul 10 09:52:39 CST 2018
     */
    int updateByPrimaryKey(ChnlPayProduct record);
}