package com.chris.demo.core.auto.mapper;

import com.chris.demo.core.auto.Xf04RecordDO;
import com.chris.demo.core.auto.Xf04RecordDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Xf04RecordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_xf04_record
     *
     * @mbg.generated Fri Sep 07 12:04:14 CST 2018
     */
    long countByExample(Xf04RecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_xf04_record
     *
     * @mbg.generated Fri Sep 07 12:04:14 CST 2018
     */
    int insert(Xf04RecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_xf04_record
     *
     * @mbg.generated Fri Sep 07 12:04:14 CST 2018
     */
    int insertSelective(Xf04RecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_xf04_record
     *
     * @mbg.generated Fri Sep 07 12:04:14 CST 2018
     */
    List<Xf04RecordDO> selectByExample(Xf04RecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_xf04_record
     *
     * @mbg.generated Fri Sep 07 12:04:14 CST 2018
     */
    int updateByExampleSelective(@Param("record") Xf04RecordDO record, @Param("example") Xf04RecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_xf04_record
     *
     * @mbg.generated Fri Sep 07 12:04:14 CST 2018
     */
    int updateByExample(@Param("record") Xf04RecordDO record, @Param("example") Xf04RecordDOExample example);
}