spring:
  application:
    name: demo-core
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/accp_payment
    username: accp_payment
    password: accp_payment
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      aop-patterns: com.chris.demo.core.*
      async-close-connection-enable: true
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
      initial-size: 30
      max-active: 150
      max-pool-prepared-statement-per-connection-size: 5
      max-wait: 1234
      min-evictable-idle-time-millis: 300001
      min-idle: 2
      pool-prepared-statements: true
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      time-between-eviction-runs-millis: 10000
      validation-query: select 1
      validation-query-timeout: 1
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
        session-stat-enable: true
        session-stat-max-count: 10
        principal-session-name: null
        principal-cookie-name: null
        profile-enable: null
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin
        allow: 192.168.1.110,127.0.0.1
        deny: 192.168.16.111
  thymeleaf:
    suffix: .html                 //指定走缀类型
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  redis:
    database: 0
    host: 192.168.110.95
    port: 6379
    password: 1234567
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
  dubbo:
    application:
      name: demo-provider
    base-package: com.chris.demo.service
    registry:
      address: 192.168.162.95
      port: 2181
    protocol:
      name: dubbo
      serialization: hessian2
    provider:
      retries: 0
mybatis:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-handlers-package: com.chris.demo.core.config
server:
  port: 8083